# CMake generated Testfile for 
# Source directory: D:/Projects/Niyah.Engine
# Build directory: D:/Projects/Niyah.Engine/build-cuda86
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("niyah_cli_help_test" "D:/Projects/Niyah.Engine/build-cuda86/Debug/niyah.exe" "--help")
  set_tests_properties("niyah_cli_help_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;176;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("niyah_cli_help_test" "D:/Projects/Niyah.Engine/build-cuda86/Release/niyah.exe" "--help")
  set_tests_properties("niyah_cli_help_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;176;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test("niyah_cli_help_test" "D:/Projects/Niyah.Engine/build-cuda86/MinSizeRel/niyah.exe" "--help")
  set_tests_properties("niyah_cli_help_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;176;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("niyah_cli_help_test" "D:/Projects/Niyah.Engine/build-cuda86/RelWithDebInfo/niyah.exe" "--help")
  set_tests_properties("niyah_cli_help_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;176;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
else()
  add_test("niyah_cli_help_test" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("niyah_cli_prepare_test" "C:/Program Files/CMake/bin/cmake.exe" "-DNIYAH_CLI=D:/Projects/Niyah.Engine/build-cuda86/Debug/niyah.exe" "-DNIYAH_TRAIN=D:/Projects/Niyah.Engine/build-cuda86/Debug/niyah-train.exe" "-DWORK_DIR=D:/Projects/Niyah.Engine/build-cuda86" "-P" "D:/Projects/Niyah.Engine/tests/check_niyah_prepare.cmake")
  set_tests_properties("niyah_cli_prepare_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;179;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("niyah_cli_prepare_test" "C:/Program Files/CMake/bin/cmake.exe" "-DNIYAH_CLI=D:/Projects/Niyah.Engine/build-cuda86/Release/niyah.exe" "-DNIYAH_TRAIN=D:/Projects/Niyah.Engine/build-cuda86/Release/niyah-train.exe" "-DWORK_DIR=D:/Projects/Niyah.Engine/build-cuda86" "-P" "D:/Projects/Niyah.Engine/tests/check_niyah_prepare.cmake")
  set_tests_properties("niyah_cli_prepare_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;179;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test("niyah_cli_prepare_test" "C:/Program Files/CMake/bin/cmake.exe" "-DNIYAH_CLI=D:/Projects/Niyah.Engine/build-cuda86/MinSizeRel/niyah.exe" "-DNIYAH_TRAIN=D:/Projects/Niyah.Engine/build-cuda86/MinSizeRel/niyah-train.exe" "-DWORK_DIR=D:/Projects/Niyah.Engine/build-cuda86" "-P" "D:/Projects/Niyah.Engine/tests/check_niyah_prepare.cmake")
  set_tests_properties("niyah_cli_prepare_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;179;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("niyah_cli_prepare_test" "C:/Program Files/CMake/bin/cmake.exe" "-DNIYAH_CLI=D:/Projects/Niyah.Engine/build-cuda86/RelWithDebInfo/niyah.exe" "-DNIYAH_TRAIN=D:/Projects/Niyah.Engine/build-cuda86/RelWithDebInfo/niyah-train.exe" "-DWORK_DIR=D:/Projects/Niyah.Engine/build-cuda86" "-P" "D:/Projects/Niyah.Engine/tests/check_niyah_prepare.cmake")
  set_tests_properties("niyah_cli_prepare_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;179;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
else()
  add_test("niyah_cli_prepare_test" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("niyah_cuda_matvec_test" "D:/Projects/Niyah.Engine/build-cuda86/Debug/niyah_cuda_matvec_test.exe")
  set_tests_properties("niyah_cuda_matvec_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;206;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("niyah_cuda_matvec_test" "D:/Projects/Niyah.Engine/build-cuda86/Release/niyah_cuda_matvec_test.exe")
  set_tests_properties("niyah_cuda_matvec_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;206;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test("niyah_cuda_matvec_test" "D:/Projects/Niyah.Engine/build-cuda86/MinSizeRel/niyah_cuda_matvec_test.exe")
  set_tests_properties("niyah_cuda_matvec_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;206;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("niyah_cuda_matvec_test" "D:/Projects/Niyah.Engine/build-cuda86/RelWithDebInfo/niyah_cuda_matvec_test.exe")
  set_tests_properties("niyah_cuda_matvec_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;206;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
else()
  add_test("niyah_cuda_matvec_test" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("niyah_cuda_model_test" "D:/Projects/Niyah.Engine/build-cuda86/Debug/niyah_cuda_model_test.exe")
  set_tests_properties("niyah_cuda_model_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;226;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("niyah_cuda_model_test" "D:/Projects/Niyah.Engine/build-cuda86/Release/niyah_cuda_model_test.exe")
  set_tests_properties("niyah_cuda_model_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;226;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test("niyah_cuda_model_test" "D:/Projects/Niyah.Engine/build-cuda86/MinSizeRel/niyah_cuda_model_test.exe")
  set_tests_properties("niyah_cuda_model_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;226;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("niyah_cuda_model_test" "D:/Projects/Niyah.Engine/build-cuda86/RelWithDebInfo/niyah_cuda_model_test.exe")
  set_tests_properties("niyah_cuda_model_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;226;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
else()
  add_test("niyah_cuda_model_test" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("niyah_cuda_decode_state_test" "D:/Projects/Niyah.Engine/build-cuda86/Debug/niyah_cuda_decode_state_test.exe")
  set_tests_properties("niyah_cuda_decode_state_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;249;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("niyah_cuda_decode_state_test" "D:/Projects/Niyah.Engine/build-cuda86/Release/niyah_cuda_decode_state_test.exe")
  set_tests_properties("niyah_cuda_decode_state_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;249;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test("niyah_cuda_decode_state_test" "D:/Projects/Niyah.Engine/build-cuda86/MinSizeRel/niyah_cuda_decode_state_test.exe")
  set_tests_properties("niyah_cuda_decode_state_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;249;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("niyah_cuda_decode_state_test" "D:/Projects/Niyah.Engine/build-cuda86/RelWithDebInfo/niyah_cuda_decode_state_test.exe")
  set_tests_properties("niyah_cuda_decode_state_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;249;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
else()
  add_test("niyah_cuda_decode_state_test" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("niyah_cuda_device_matvec_test" "D:/Projects/Niyah.Engine/build-cuda86/Debug/niyah_cuda_device_matvec_test.exe")
  set_tests_properties("niyah_cuda_device_matvec_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;276;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("niyah_cuda_device_matvec_test" "D:/Projects/Niyah.Engine/build-cuda86/Release/niyah_cuda_device_matvec_test.exe")
  set_tests_properties("niyah_cuda_device_matvec_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;276;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test("niyah_cuda_device_matvec_test" "D:/Projects/Niyah.Engine/build-cuda86/MinSizeRel/niyah_cuda_device_matvec_test.exe")
  set_tests_properties("niyah_cuda_device_matvec_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;276;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("niyah_cuda_device_matvec_test" "D:/Projects/Niyah.Engine/build-cuda86/RelWithDebInfo/niyah_cuda_device_matvec_test.exe")
  set_tests_properties("niyah_cuda_device_matvec_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;276;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
else()
  add_test("niyah_cuda_device_matvec_test" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("niyah_cuda_decode_token_test" "D:/Projects/Niyah.Engine/build-cuda86/Debug/niyah_cuda_decode_token_test.exe")
  set_tests_properties("niyah_cuda_decode_token_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;303;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("niyah_cuda_decode_token_test" "D:/Projects/Niyah.Engine/build-cuda86/Release/niyah_cuda_decode_token_test.exe")
  set_tests_properties("niyah_cuda_decode_token_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;303;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test("niyah_cuda_decode_token_test" "D:/Projects/Niyah.Engine/build-cuda86/MinSizeRel/niyah_cuda_decode_token_test.exe")
  set_tests_properties("niyah_cuda_decode_token_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;303;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("niyah_cuda_decode_token_test" "D:/Projects/Niyah.Engine/build-cuda86/RelWithDebInfo/niyah_cuda_decode_token_test.exe")
  set_tests_properties("niyah_cuda_decode_token_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;303;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
else()
  add_test("niyah_cuda_decode_token_test" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("niyah_cuda_generation_test" "D:/Projects/Niyah.Engine/build-cuda86/Debug/niyah_cuda_generation_test.exe")
  set_tests_properties("niyah_cuda_generation_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;330;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("niyah_cuda_generation_test" "D:/Projects/Niyah.Engine/build-cuda86/Release/niyah_cuda_generation_test.exe")
  set_tests_properties("niyah_cuda_generation_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;330;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test("niyah_cuda_generation_test" "D:/Projects/Niyah.Engine/build-cuda86/MinSizeRel/niyah_cuda_generation_test.exe")
  set_tests_properties("niyah_cuda_generation_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;330;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("niyah_cuda_generation_test" "D:/Projects/Niyah.Engine/build-cuda86/RelWithDebInfo/niyah_cuda_generation_test.exe")
  set_tests_properties("niyah_cuda_generation_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;330;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
else()
  add_test("niyah_cuda_generation_test" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("niyah_model_test" "D:/Projects/Niyah.Engine/build-cuda86/Debug/niyah_model_test.exe")
  set_tests_properties("niyah_model_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;425;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("niyah_model_test" "D:/Projects/Niyah.Engine/build-cuda86/Release/niyah_model_test.exe")
  set_tests_properties("niyah_model_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;425;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test("niyah_model_test" "D:/Projects/Niyah.Engine/build-cuda86/MinSizeRel/niyah_model_test.exe")
  set_tests_properties("niyah_model_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;425;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("niyah_model_test" "D:/Projects/Niyah.Engine/build-cuda86/RelWithDebInfo/niyah_model_test.exe")
  set_tests_properties("niyah_model_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;425;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
else()
  add_test("niyah_model_test" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("niyah_tokenizer_test" "D:/Projects/Niyah.Engine/build-cuda86/Debug/niyah_tokenizer_test.exe")
  set_tests_properties("niyah_tokenizer_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;426;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("niyah_tokenizer_test" "D:/Projects/Niyah.Engine/build-cuda86/Release/niyah_tokenizer_test.exe")
  set_tests_properties("niyah_tokenizer_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;426;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test("niyah_tokenizer_test" "D:/Projects/Niyah.Engine/build-cuda86/MinSizeRel/niyah_tokenizer_test.exe")
  set_tests_properties("niyah_tokenizer_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;426;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("niyah_tokenizer_test" "D:/Projects/Niyah.Engine/build-cuda86/RelWithDebInfo/niyah_tokenizer_test.exe")
  set_tests_properties("niyah_tokenizer_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;426;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
else()
  add_test("niyah_tokenizer_test" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("niyah_dataset_test" "D:/Projects/Niyah.Engine/build-cuda86/Debug/niyah_dataset_test.exe")
  set_tests_properties("niyah_dataset_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;427;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("niyah_dataset_test" "D:/Projects/Niyah.Engine/build-cuda86/Release/niyah_dataset_test.exe")
  set_tests_properties("niyah_dataset_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;427;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test("niyah_dataset_test" "D:/Projects/Niyah.Engine/build-cuda86/MinSizeRel/niyah_dataset_test.exe")
  set_tests_properties("niyah_dataset_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;427;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("niyah_dataset_test" "D:/Projects/Niyah.Engine/build-cuda86/RelWithDebInfo/niyah_dataset_test.exe")
  set_tests_properties("niyah_dataset_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;427;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
else()
  add_test("niyah_dataset_test" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("niyah_dataset_shard_test" "D:/Projects/Niyah.Engine/build-cuda86/Debug/niyah_dataset_shard_test.exe")
  set_tests_properties("niyah_dataset_shard_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;428;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("niyah_dataset_shard_test" "D:/Projects/Niyah.Engine/build-cuda86/Release/niyah_dataset_shard_test.exe")
  set_tests_properties("niyah_dataset_shard_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;428;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test("niyah_dataset_shard_test" "D:/Projects/Niyah.Engine/build-cuda86/MinSizeRel/niyah_dataset_shard_test.exe")
  set_tests_properties("niyah_dataset_shard_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;428;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("niyah_dataset_shard_test" "D:/Projects/Niyah.Engine/build-cuda86/RelWithDebInfo/niyah_dataset_shard_test.exe")
  set_tests_properties("niyah_dataset_shard_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;428;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
else()
  add_test("niyah_dataset_shard_test" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("niyah_dataset_collection_test" "D:/Projects/Niyah.Engine/build-cuda86/Debug/niyah_dataset_collection_test.exe")
  set_tests_properties("niyah_dataset_collection_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;429;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("niyah_dataset_collection_test" "D:/Projects/Niyah.Engine/build-cuda86/Release/niyah_dataset_collection_test.exe")
  set_tests_properties("niyah_dataset_collection_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;429;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test("niyah_dataset_collection_test" "D:/Projects/Niyah.Engine/build-cuda86/MinSizeRel/niyah_dataset_collection_test.exe")
  set_tests_properties("niyah_dataset_collection_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;429;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("niyah_dataset_collection_test" "D:/Projects/Niyah.Engine/build-cuda86/RelWithDebInfo/niyah_dataset_collection_test.exe")
  set_tests_properties("niyah_dataset_collection_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;429;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
else()
  add_test("niyah_dataset_collection_test" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("niyah_transformer_test" "D:/Projects/Niyah.Engine/build-cuda86/Debug/niyah_transformer_test.exe")
  set_tests_properties("niyah_transformer_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;430;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("niyah_transformer_test" "D:/Projects/Niyah.Engine/build-cuda86/Release/niyah_transformer_test.exe")
  set_tests_properties("niyah_transformer_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;430;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test("niyah_transformer_test" "D:/Projects/Niyah.Engine/build-cuda86/MinSizeRel/niyah_transformer_test.exe")
  set_tests_properties("niyah_transformer_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;430;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("niyah_transformer_test" "D:/Projects/Niyah.Engine/build-cuda86/RelWithDebInfo/niyah_transformer_test.exe")
  set_tests_properties("niyah_transformer_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;430;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
else()
  add_test("niyah_transformer_test" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("niyah_decode_test" "D:/Projects/Niyah.Engine/build-cuda86/Debug/niyah_decode_test.exe")
  set_tests_properties("niyah_decode_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;431;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("niyah_decode_test" "D:/Projects/Niyah.Engine/build-cuda86/Release/niyah_decode_test.exe")
  set_tests_properties("niyah_decode_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;431;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test("niyah_decode_test" "D:/Projects/Niyah.Engine/build-cuda86/MinSizeRel/niyah_decode_test.exe")
  set_tests_properties("niyah_decode_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;431;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("niyah_decode_test" "D:/Projects/Niyah.Engine/build-cuda86/RelWithDebInfo/niyah_decode_test.exe")
  set_tests_properties("niyah_decode_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;431;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
else()
  add_test("niyah_decode_test" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("niyah_generation_test" "D:/Projects/Niyah.Engine/build-cuda86/Debug/niyah_generation_test.exe")
  set_tests_properties("niyah_generation_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;432;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("niyah_generation_test" "D:/Projects/Niyah.Engine/build-cuda86/Release/niyah_generation_test.exe")
  set_tests_properties("niyah_generation_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;432;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test("niyah_generation_test" "D:/Projects/Niyah.Engine/build-cuda86/MinSizeRel/niyah_generation_test.exe")
  set_tests_properties("niyah_generation_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;432;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("niyah_generation_test" "D:/Projects/Niyah.Engine/build-cuda86/RelWithDebInfo/niyah_generation_test.exe")
  set_tests_properties("niyah_generation_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;432;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
else()
  add_test("niyah_generation_test" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("niyah_train_test" "D:/Projects/Niyah.Engine/build-cuda86/Debug/niyah_train_test.exe")
  set_tests_properties("niyah_train_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;433;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("niyah_train_test" "D:/Projects/Niyah.Engine/build-cuda86/Release/niyah_train_test.exe")
  set_tests_properties("niyah_train_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;433;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test("niyah_train_test" "D:/Projects/Niyah.Engine/build-cuda86/MinSizeRel/niyah_train_test.exe")
  set_tests_properties("niyah_train_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;433;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("niyah_train_test" "D:/Projects/Niyah.Engine/build-cuda86/RelWithDebInfo/niyah_train_test.exe")
  set_tests_properties("niyah_train_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;433;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
else()
  add_test("niyah_train_test" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("niyah_eval_test" "D:/Projects/Niyah.Engine/build-cuda86/Debug/niyah_eval_test.exe")
  set_tests_properties("niyah_eval_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;434;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("niyah_eval_test" "D:/Projects/Niyah.Engine/build-cuda86/Release/niyah_eval_test.exe")
  set_tests_properties("niyah_eval_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;434;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test("niyah_eval_test" "D:/Projects/Niyah.Engine/build-cuda86/MinSizeRel/niyah_eval_test.exe")
  set_tests_properties("niyah_eval_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;434;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("niyah_eval_test" "D:/Projects/Niyah.Engine/build-cuda86/RelWithDebInfo/niyah_eval_test.exe")
  set_tests_properties("niyah_eval_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;434;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
else()
  add_test("niyah_eval_test" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("niyah_training_loop_test" "D:/Projects/Niyah.Engine/build-cuda86/Debug/niyah_training_loop_test.exe")
  set_tests_properties("niyah_training_loop_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;435;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("niyah_training_loop_test" "D:/Projects/Niyah.Engine/build-cuda86/Release/niyah_training_loop_test.exe")
  set_tests_properties("niyah_training_loop_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;435;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test("niyah_training_loop_test" "D:/Projects/Niyah.Engine/build-cuda86/MinSizeRel/niyah_training_loop_test.exe")
  set_tests_properties("niyah_training_loop_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;435;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("niyah_training_loop_test" "D:/Projects/Niyah.Engine/build-cuda86/RelWithDebInfo/niyah_training_loop_test.exe")
  set_tests_properties("niyah_training_loop_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;435;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
else()
  add_test("niyah_training_loop_test" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("niyah_backward_test" "D:/Projects/Niyah.Engine/build-cuda86/Debug/niyah_backward_test.exe")
  set_tests_properties("niyah_backward_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;436;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("niyah_backward_test" "D:/Projects/Niyah.Engine/build-cuda86/Release/niyah_backward_test.exe")
  set_tests_properties("niyah_backward_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;436;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test("niyah_backward_test" "D:/Projects/Niyah.Engine/build-cuda86/MinSizeRel/niyah_backward_test.exe")
  set_tests_properties("niyah_backward_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;436;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("niyah_backward_test" "D:/Projects/Niyah.Engine/build-cuda86/RelWithDebInfo/niyah_backward_test.exe")
  set_tests_properties("niyah_backward_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;436;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
else()
  add_test("niyah_backward_test" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("niyah_text_pipeline_test" "D:/Projects/Niyah.Engine/build-cuda86/Debug/niyah_text_pipeline_test.exe")
  set_tests_properties("niyah_text_pipeline_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;437;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("niyah_text_pipeline_test" "D:/Projects/Niyah.Engine/build-cuda86/Release/niyah_text_pipeline_test.exe")
  set_tests_properties("niyah_text_pipeline_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;437;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test("niyah_text_pipeline_test" "D:/Projects/Niyah.Engine/build-cuda86/MinSizeRel/niyah_text_pipeline_test.exe")
  set_tests_properties("niyah_text_pipeline_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;437;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("niyah_text_pipeline_test" "D:/Projects/Niyah.Engine/build-cuda86/RelWithDebInfo/niyah_text_pipeline_test.exe")
  set_tests_properties("niyah_text_pipeline_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;437;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
else()
  add_test("niyah_text_pipeline_test" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("niyah_optimizer_test" "D:/Projects/Niyah.Engine/build-cuda86/Debug/niyah_optimizer_test.exe")
  set_tests_properties("niyah_optimizer_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;438;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("niyah_optimizer_test" "D:/Projects/Niyah.Engine/build-cuda86/Release/niyah_optimizer_test.exe")
  set_tests_properties("niyah_optimizer_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;438;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test("niyah_optimizer_test" "D:/Projects/Niyah.Engine/build-cuda86/MinSizeRel/niyah_optimizer_test.exe")
  set_tests_properties("niyah_optimizer_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;438;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("niyah_optimizer_test" "D:/Projects/Niyah.Engine/build-cuda86/RelWithDebInfo/niyah_optimizer_test.exe")
  set_tests_properties("niyah_optimizer_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;438;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
else()
  add_test("niyah_optimizer_test" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("niyah_checkpoint_test" "D:/Projects/Niyah.Engine/build-cuda86/Debug/niyah_checkpoint_test.exe")
  set_tests_properties("niyah_checkpoint_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;439;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("niyah_checkpoint_test" "D:/Projects/Niyah.Engine/build-cuda86/Release/niyah_checkpoint_test.exe")
  set_tests_properties("niyah_checkpoint_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;439;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test("niyah_checkpoint_test" "D:/Projects/Niyah.Engine/build-cuda86/MinSizeRel/niyah_checkpoint_test.exe")
  set_tests_properties("niyah_checkpoint_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;439;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("niyah_checkpoint_test" "D:/Projects/Niyah.Engine/build-cuda86/RelWithDebInfo/niyah_checkpoint_test.exe")
  set_tests_properties("niyah_checkpoint_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;439;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
else()
  add_test("niyah_checkpoint_test" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("niyah_segment_embeddings_test" "D:/Projects/Niyah.Engine/build-cuda86/Debug/niyah_segment_embeddings_test.exe")
  set_tests_properties("niyah_segment_embeddings_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;440;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("niyah_segment_embeddings_test" "D:/Projects/Niyah.Engine/build-cuda86/Release/niyah_segment_embeddings_test.exe")
  set_tests_properties("niyah_segment_embeddings_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;440;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test("niyah_segment_embeddings_test" "D:/Projects/Niyah.Engine/build-cuda86/MinSizeRel/niyah_segment_embeddings_test.exe")
  set_tests_properties("niyah_segment_embeddings_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;440;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("niyah_segment_embeddings_test" "D:/Projects/Niyah.Engine/build-cuda86/RelWithDebInfo/niyah_segment_embeddings_test.exe")
  set_tests_properties("niyah_segment_embeddings_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;440;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
else()
  add_test("niyah_segment_embeddings_test" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("niyah_train_help_test" "D:/Projects/Niyah.Engine/build-cuda86/Debug/niyah-train.exe" "--help")
  set_tests_properties("niyah_train_help_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;452;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("niyah_train_help_test" "D:/Projects/Niyah.Engine/build-cuda86/Release/niyah-train.exe" "--help")
  set_tests_properties("niyah_train_help_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;452;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test("niyah_train_help_test" "D:/Projects/Niyah.Engine/build-cuda86/MinSizeRel/niyah-train.exe" "--help")
  set_tests_properties("niyah_train_help_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;452;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("niyah_train_help_test" "D:/Projects/Niyah.Engine/build-cuda86/RelWithDebInfo/niyah-train.exe" "--help")
  set_tests_properties("niyah_train_help_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;452;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
else()
  add_test("niyah_train_help_test" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("niyah_training_fixture_test" "D:/Projects/Niyah.Engine/build-cuda86/Debug/niyah_training_fixture.exe" "D:/Projects/Niyah.Engine/build-cuda86/niyah_train_fixture.tok" "D:/Projects/Niyah.Engine/build-cuda86/niyah_train_fixture.srd" "D:/Projects/Niyah.Engine/build-cuda86/niyah_train_fixture_alt.srd" "D:/Projects/Niyah.Engine/build-cuda86/niyah_train_fixture_1.ckpt" "D:/Projects/Niyah.Engine/build-cuda86/niyah_train_fixture_1.cursor" "D:/Projects/Niyah.Engine/build-cuda86/niyah_train_fixture_2.ckpt" "D:/Projects/Niyah.Engine/build-cuda86/niyah_train_fixture_2.cursor")
  set_tests_properties("niyah_training_fixture_test" PROPERTIES  FIXTURES_SETUP "niyah_train_files" _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;454;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("niyah_training_fixture_test" "D:/Projects/Niyah.Engine/build-cuda86/Release/niyah_training_fixture.exe" "D:/Projects/Niyah.Engine/build-cuda86/niyah_train_fixture.tok" "D:/Projects/Niyah.Engine/build-cuda86/niyah_train_fixture.srd" "D:/Projects/Niyah.Engine/build-cuda86/niyah_train_fixture_alt.srd" "D:/Projects/Niyah.Engine/build-cuda86/niyah_train_fixture_1.ckpt" "D:/Projects/Niyah.Engine/build-cuda86/niyah_train_fixture_1.cursor" "D:/Projects/Niyah.Engine/build-cuda86/niyah_train_fixture_2.ckpt" "D:/Projects/Niyah.Engine/build-cuda86/niyah_train_fixture_2.cursor")
  set_tests_properties("niyah_training_fixture_test" PROPERTIES  FIXTURES_SETUP "niyah_train_files" _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;454;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test("niyah_training_fixture_test" "D:/Projects/Niyah.Engine/build-cuda86/MinSizeRel/niyah_training_fixture.exe" "D:/Projects/Niyah.Engine/build-cuda86/niyah_train_fixture.tok" "D:/Projects/Niyah.Engine/build-cuda86/niyah_train_fixture.srd" "D:/Projects/Niyah.Engine/build-cuda86/niyah_train_fixture_alt.srd" "D:/Projects/Niyah.Engine/build-cuda86/niyah_train_fixture_1.ckpt" "D:/Projects/Niyah.Engine/build-cuda86/niyah_train_fixture_1.cursor" "D:/Projects/Niyah.Engine/build-cuda86/niyah_train_fixture_2.ckpt" "D:/Projects/Niyah.Engine/build-cuda86/niyah_train_fixture_2.cursor")
  set_tests_properties("niyah_training_fixture_test" PROPERTIES  FIXTURES_SETUP "niyah_train_files" _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;454;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("niyah_training_fixture_test" "D:/Projects/Niyah.Engine/build-cuda86/RelWithDebInfo/niyah_training_fixture.exe" "D:/Projects/Niyah.Engine/build-cuda86/niyah_train_fixture.tok" "D:/Projects/Niyah.Engine/build-cuda86/niyah_train_fixture.srd" "D:/Projects/Niyah.Engine/build-cuda86/niyah_train_fixture_alt.srd" "D:/Projects/Niyah.Engine/build-cuda86/niyah_train_fixture_1.ckpt" "D:/Projects/Niyah.Engine/build-cuda86/niyah_train_fixture_1.cursor" "D:/Projects/Niyah.Engine/build-cuda86/niyah_train_fixture_2.ckpt" "D:/Projects/Niyah.Engine/build-cuda86/niyah_train_fixture_2.cursor")
  set_tests_properties("niyah_training_fixture_test" PROPERTIES  FIXTURES_SETUP "niyah_train_files" _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;454;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
else()
  add_test("niyah_training_fixture_test" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("niyah_train_new_test" "D:/Projects/Niyah.Engine/build-cuda86/Debug/niyah-train.exe" "new" "--tokenizer" "D:/Projects/Niyah.Engine/build-cuda86/niyah_train_fixture.tok" "--shard" "D:/Projects/Niyah.Engine/build-cuda86/niyah_train_fixture.srd" "--checkpoint-out" "D:/Projects/Niyah.Engine/build-cuda86/niyah_train_fixture_1.ckpt" "--cursor-out" "D:/Projects/Niyah.Engine/build-cuda86/niyah_train_fixture_1.cursor" "--updates" "2" "--batch-size" "1" "--accumulation-steps" "1" "--model-seed" "42" "--data-seed" "7" "--context-length" "4" "--embedding-dim" "8" "--layers" "1" "--heads" "2" "--kv-heads" "1" "--ffn-hidden-dim" "16" "--rms-norm-eps" "0.00001" "--tie-word-embeddings" "1" "--learning-rate" "0.001" "--beta1" "0.9" "--beta2" "0.999" "--epsilon" "0.00000001" "--weight-decay" "0.0" "--max-grad-norm" "1.0")
  set_tests_properties("niyah_train_new_test" PROPERTIES  FIXTURES_REQUIRED "niyah_train_files" _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;463;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("niyah_train_new_test" "D:/Projects/Niyah.Engine/build-cuda86/Release/niyah-train.exe" "new" "--tokenizer" "D:/Projects/Niyah.Engine/build-cuda86/niyah_train_fixture.tok" "--shard" "D:/Projects/Niyah.Engine/build-cuda86/niyah_train_fixture.srd" "--checkpoint-out" "D:/Projects/Niyah.Engine/build-cuda86/niyah_train_fixture_1.ckpt" "--cursor-out" "D:/Projects/Niyah.Engine/build-cuda86/niyah_train_fixture_1.cursor" "--updates" "2" "--batch-size" "1" "--accumulation-steps" "1" "--model-seed" "42" "--data-seed" "7" "--context-length" "4" "--embedding-dim" "8" "--layers" "1" "--heads" "2" "--kv-heads" "1" "--ffn-hidden-dim" "16" "--rms-norm-eps" "0.00001" "--tie-word-embeddings" "1" "--learning-rate" "0.001" "--beta1" "0.9" "--beta2" "0.999" "--epsilon" "0.00000001" "--weight-decay" "0.0" "--max-grad-norm" "1.0")
  set_tests_properties("niyah_train_new_test" PROPERTIES  FIXTURES_REQUIRED "niyah_train_files" _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;463;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test("niyah_train_new_test" "D:/Projects/Niyah.Engine/build-cuda86/MinSizeRel/niyah-train.exe" "new" "--tokenizer" "D:/Projects/Niyah.Engine/build-cuda86/niyah_train_fixture.tok" "--shard" "D:/Projects/Niyah.Engine/build-cuda86/niyah_train_fixture.srd" "--checkpoint-out" "D:/Projects/Niyah.Engine/build-cuda86/niyah_train_fixture_1.ckpt" "--cursor-out" "D:/Projects/Niyah.Engine/build-cuda86/niyah_train_fixture_1.cursor" "--updates" "2" "--batch-size" "1" "--accumulation-steps" "1" "--model-seed" "42" "--data-seed" "7" "--context-length" "4" "--embedding-dim" "8" "--layers" "1" "--heads" "2" "--kv-heads" "1" "--ffn-hidden-dim" "16" "--rms-norm-eps" "0.00001" "--tie-word-embeddings" "1" "--learning-rate" "0.001" "--beta1" "0.9" "--beta2" "0.999" "--epsilon" "0.00000001" "--weight-decay" "0.0" "--max-grad-norm" "1.0")
  set_tests_properties("niyah_train_new_test" PROPERTIES  FIXTURES_REQUIRED "niyah_train_files" _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;463;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("niyah_train_new_test" "D:/Projects/Niyah.Engine/build-cuda86/RelWithDebInfo/niyah-train.exe" "new" "--tokenizer" "D:/Projects/Niyah.Engine/build-cuda86/niyah_train_fixture.tok" "--shard" "D:/Projects/Niyah.Engine/build-cuda86/niyah_train_fixture.srd" "--checkpoint-out" "D:/Projects/Niyah.Engine/build-cuda86/niyah_train_fixture_1.ckpt" "--cursor-out" "D:/Projects/Niyah.Engine/build-cuda86/niyah_train_fixture_1.cursor" "--updates" "2" "--batch-size" "1" "--accumulation-steps" "1" "--model-seed" "42" "--data-seed" "7" "--context-length" "4" "--embedding-dim" "8" "--layers" "1" "--heads" "2" "--kv-heads" "1" "--ffn-hidden-dim" "16" "--rms-norm-eps" "0.00001" "--tie-word-embeddings" "1" "--learning-rate" "0.001" "--beta1" "0.9" "--beta2" "0.999" "--epsilon" "0.00000001" "--weight-decay" "0.0" "--max-grad-norm" "1.0")
  set_tests_properties("niyah_train_new_test" PROPERTIES  FIXTURES_REQUIRED "niyah_train_files" _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;463;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
else()
  add_test("niyah_train_new_test" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("niyah_cli_run_test" "C:/Program Files/CMake/bin/cmake.exe" "-DNIYAH_FIXTURE=D:/Projects/Niyah.Engine/build-cuda86/Debug/niyah_training_fixture.exe" "-DNIYAH_TRAIN=D:/Projects/Niyah.Engine/build-cuda86/Debug/niyah-train.exe" "-DNIYAH_CLI=D:/Projects/Niyah.Engine/build-cuda86/Debug/niyah.exe" "-DWORK_DIR=D:/Projects/Niyah.Engine/build-cuda86" "-DBACKEND=cpu" "-P" "D:/Projects/Niyah.Engine/tests/check_niyah_run.cmake")
  set_tests_properties("niyah_cli_run_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;491;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("niyah_cli_run_test" "C:/Program Files/CMake/bin/cmake.exe" "-DNIYAH_FIXTURE=D:/Projects/Niyah.Engine/build-cuda86/Release/niyah_training_fixture.exe" "-DNIYAH_TRAIN=D:/Projects/Niyah.Engine/build-cuda86/Release/niyah-train.exe" "-DNIYAH_CLI=D:/Projects/Niyah.Engine/build-cuda86/Release/niyah.exe" "-DWORK_DIR=D:/Projects/Niyah.Engine/build-cuda86" "-DBACKEND=cpu" "-P" "D:/Projects/Niyah.Engine/tests/check_niyah_run.cmake")
  set_tests_properties("niyah_cli_run_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;491;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test("niyah_cli_run_test" "C:/Program Files/CMake/bin/cmake.exe" "-DNIYAH_FIXTURE=D:/Projects/Niyah.Engine/build-cuda86/MinSizeRel/niyah_training_fixture.exe" "-DNIYAH_TRAIN=D:/Projects/Niyah.Engine/build-cuda86/MinSizeRel/niyah-train.exe" "-DNIYAH_CLI=D:/Projects/Niyah.Engine/build-cuda86/MinSizeRel/niyah.exe" "-DWORK_DIR=D:/Projects/Niyah.Engine/build-cuda86" "-DBACKEND=cpu" "-P" "D:/Projects/Niyah.Engine/tests/check_niyah_run.cmake")
  set_tests_properties("niyah_cli_run_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;491;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("niyah_cli_run_test" "C:/Program Files/CMake/bin/cmake.exe" "-DNIYAH_FIXTURE=D:/Projects/Niyah.Engine/build-cuda86/RelWithDebInfo/niyah_training_fixture.exe" "-DNIYAH_TRAIN=D:/Projects/Niyah.Engine/build-cuda86/RelWithDebInfo/niyah-train.exe" "-DNIYAH_CLI=D:/Projects/Niyah.Engine/build-cuda86/RelWithDebInfo/niyah.exe" "-DWORK_DIR=D:/Projects/Niyah.Engine/build-cuda86" "-DBACKEND=cpu" "-P" "D:/Projects/Niyah.Engine/tests/check_niyah_run.cmake")
  set_tests_properties("niyah_cli_run_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;491;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
else()
  add_test("niyah_cli_run_test" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("niyah_cli_cuda_run_test" "C:/Program Files/CMake/bin/cmake.exe" "-DNIYAH_FIXTURE=D:/Projects/Niyah.Engine/build-cuda86/Debug/niyah_training_fixture.exe" "-DNIYAH_TRAIN=D:/Projects/Niyah.Engine/build-cuda86/Debug/niyah-train.exe" "-DNIYAH_CLI=D:/Projects/Niyah.Engine/build-cuda86/Debug/niyah.exe" "-DWORK_DIR=D:/Projects/Niyah.Engine/build-cuda86" "-DBACKEND=cuda" "-P" "D:/Projects/Niyah.Engine/tests/check_niyah_run.cmake")
  set_tests_properties("niyah_cli_cuda_run_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;501;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("niyah_cli_cuda_run_test" "C:/Program Files/CMake/bin/cmake.exe" "-DNIYAH_FIXTURE=D:/Projects/Niyah.Engine/build-cuda86/Release/niyah_training_fixture.exe" "-DNIYAH_TRAIN=D:/Projects/Niyah.Engine/build-cuda86/Release/niyah-train.exe" "-DNIYAH_CLI=D:/Projects/Niyah.Engine/build-cuda86/Release/niyah.exe" "-DWORK_DIR=D:/Projects/Niyah.Engine/build-cuda86" "-DBACKEND=cuda" "-P" "D:/Projects/Niyah.Engine/tests/check_niyah_run.cmake")
  set_tests_properties("niyah_cli_cuda_run_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;501;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test("niyah_cli_cuda_run_test" "C:/Program Files/CMake/bin/cmake.exe" "-DNIYAH_FIXTURE=D:/Projects/Niyah.Engine/build-cuda86/MinSizeRel/niyah_training_fixture.exe" "-DNIYAH_TRAIN=D:/Projects/Niyah.Engine/build-cuda86/MinSizeRel/niyah-train.exe" "-DNIYAH_CLI=D:/Projects/Niyah.Engine/build-cuda86/MinSizeRel/niyah.exe" "-DWORK_DIR=D:/Projects/Niyah.Engine/build-cuda86" "-DBACKEND=cuda" "-P" "D:/Projects/Niyah.Engine/tests/check_niyah_run.cmake")
  set_tests_properties("niyah_cli_cuda_run_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;501;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("niyah_cli_cuda_run_test" "C:/Program Files/CMake/bin/cmake.exe" "-DNIYAH_FIXTURE=D:/Projects/Niyah.Engine/build-cuda86/RelWithDebInfo/niyah_training_fixture.exe" "-DNIYAH_TRAIN=D:/Projects/Niyah.Engine/build-cuda86/RelWithDebInfo/niyah-train.exe" "-DNIYAH_CLI=D:/Projects/Niyah.Engine/build-cuda86/RelWithDebInfo/niyah.exe" "-DWORK_DIR=D:/Projects/Niyah.Engine/build-cuda86" "-DBACKEND=cuda" "-P" "D:/Projects/Niyah.Engine/tests/check_niyah_run.cmake")
  set_tests_properties("niyah_cli_cuda_run_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;501;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
else()
  add_test("niyah_cli_cuda_run_test" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("niyah_train_resume_test" "D:/Projects/Niyah.Engine/build-cuda86/Debug/niyah-train.exe" "resume" "--tokenizer" "D:/Projects/Niyah.Engine/build-cuda86/niyah_train_fixture.tok" "--shard" "D:/Projects/Niyah.Engine/build-cuda86/niyah_train_fixture.srd" "--checkpoint-in" "D:/Projects/Niyah.Engine/build-cuda86/niyah_train_fixture_1.ckpt" "--cursor-in" "D:/Projects/Niyah.Engine/build-cuda86/niyah_train_fixture_1.cursor" "--checkpoint-out" "D:/Projects/Niyah.Engine/build-cuda86/niyah_train_fixture_2.ckpt" "--cursor-out" "D:/Projects/Niyah.Engine/build-cuda86/niyah_train_fixture_2.cursor" "--updates" "2" "--batch-size" "1" "--accumulation-steps" "1")
  set_tests_properties("niyah_train_resume_test" PROPERTIES  DEPENDS "niyah_train_new_test" FIXTURES_REQUIRED "niyah_train_files" _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;523;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("niyah_train_resume_test" "D:/Projects/Niyah.Engine/build-cuda86/Release/niyah-train.exe" "resume" "--tokenizer" "D:/Projects/Niyah.Engine/build-cuda86/niyah_train_fixture.tok" "--shard" "D:/Projects/Niyah.Engine/build-cuda86/niyah_train_fixture.srd" "--checkpoint-in" "D:/Projects/Niyah.Engine/build-cuda86/niyah_train_fixture_1.ckpt" "--cursor-in" "D:/Projects/Niyah.Engine/build-cuda86/niyah_train_fixture_1.cursor" "--checkpoint-out" "D:/Projects/Niyah.Engine/build-cuda86/niyah_train_fixture_2.ckpt" "--cursor-out" "D:/Projects/Niyah.Engine/build-cuda86/niyah_train_fixture_2.cursor" "--updates" "2" "--batch-size" "1" "--accumulation-steps" "1")
  set_tests_properties("niyah_train_resume_test" PROPERTIES  DEPENDS "niyah_train_new_test" FIXTURES_REQUIRED "niyah_train_files" _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;523;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test("niyah_train_resume_test" "D:/Projects/Niyah.Engine/build-cuda86/MinSizeRel/niyah-train.exe" "resume" "--tokenizer" "D:/Projects/Niyah.Engine/build-cuda86/niyah_train_fixture.tok" "--shard" "D:/Projects/Niyah.Engine/build-cuda86/niyah_train_fixture.srd" "--checkpoint-in" "D:/Projects/Niyah.Engine/build-cuda86/niyah_train_fixture_1.ckpt" "--cursor-in" "D:/Projects/Niyah.Engine/build-cuda86/niyah_train_fixture_1.cursor" "--checkpoint-out" "D:/Projects/Niyah.Engine/build-cuda86/niyah_train_fixture_2.ckpt" "--cursor-out" "D:/Projects/Niyah.Engine/build-cuda86/niyah_train_fixture_2.cursor" "--updates" "2" "--batch-size" "1" "--accumulation-steps" "1")
  set_tests_properties("niyah_train_resume_test" PROPERTIES  DEPENDS "niyah_train_new_test" FIXTURES_REQUIRED "niyah_train_files" _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;523;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("niyah_train_resume_test" "D:/Projects/Niyah.Engine/build-cuda86/RelWithDebInfo/niyah-train.exe" "resume" "--tokenizer" "D:/Projects/Niyah.Engine/build-cuda86/niyah_train_fixture.tok" "--shard" "D:/Projects/Niyah.Engine/build-cuda86/niyah_train_fixture.srd" "--checkpoint-in" "D:/Projects/Niyah.Engine/build-cuda86/niyah_train_fixture_1.ckpt" "--cursor-in" "D:/Projects/Niyah.Engine/build-cuda86/niyah_train_fixture_1.cursor" "--checkpoint-out" "D:/Projects/Niyah.Engine/build-cuda86/niyah_train_fixture_2.ckpt" "--cursor-out" "D:/Projects/Niyah.Engine/build-cuda86/niyah_train_fixture_2.cursor" "--updates" "2" "--batch-size" "1" "--accumulation-steps" "1")
  set_tests_properties("niyah_train_resume_test" PROPERTIES  DEPENDS "niyah_train_new_test" FIXTURES_REQUIRED "niyah_train_files" _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;523;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
else()
  add_test("niyah_train_resume_test" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("niyah_train_resume_dataset_mismatch_test" "C:/Program Files/CMake/bin/cmake.exe" "-DNIYAH_TRAIN_EXE=D:/Projects/Niyah.Engine/build-cuda86/Debug/niyah-train.exe" "-DNIYAH_TRAIN_TOK=D:/Projects/Niyah.Engine/build-cuda86/niyah_train_fixture.tok" "-DNIYAH_TRAIN_SHARD=D:/Projects/Niyah.Engine/build-cuda86/niyah_train_fixture.srd" "-DNIYAH_TRAIN_SHARD_ALT=D:/Projects/Niyah.Engine/build-cuda86/niyah_train_fixture_alt.srd" "-DNIYAH_TRAIN_CKPT=D:/Projects/Niyah.Engine/build-cuda86/niyah_train_fixture_3.ckpt" "-DNIYAH_TRAIN_CUR=D:/Projects/Niyah.Engine/build-cuda86/niyah_train_fixture_3.cursor" "-P" "D:/Projects/Niyah.Engine/tests/check_train_resume_mismatch.cmake")
  set_tests_properties("niyah_train_resume_dataset_mismatch_test" PROPERTIES  FIXTURES_REQUIRED "niyah_train_files" _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;538;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("niyah_train_resume_dataset_mismatch_test" "C:/Program Files/CMake/bin/cmake.exe" "-DNIYAH_TRAIN_EXE=D:/Projects/Niyah.Engine/build-cuda86/Release/niyah-train.exe" "-DNIYAH_TRAIN_TOK=D:/Projects/Niyah.Engine/build-cuda86/niyah_train_fixture.tok" "-DNIYAH_TRAIN_SHARD=D:/Projects/Niyah.Engine/build-cuda86/niyah_train_fixture.srd" "-DNIYAH_TRAIN_SHARD_ALT=D:/Projects/Niyah.Engine/build-cuda86/niyah_train_fixture_alt.srd" "-DNIYAH_TRAIN_CKPT=D:/Projects/Niyah.Engine/build-cuda86/niyah_train_fixture_3.ckpt" "-DNIYAH_TRAIN_CUR=D:/Projects/Niyah.Engine/build-cuda86/niyah_train_fixture_3.cursor" "-P" "D:/Projects/Niyah.Engine/tests/check_train_resume_mismatch.cmake")
  set_tests_properties("niyah_train_resume_dataset_mismatch_test" PROPERTIES  FIXTURES_REQUIRED "niyah_train_files" _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;538;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test("niyah_train_resume_dataset_mismatch_test" "C:/Program Files/CMake/bin/cmake.exe" "-DNIYAH_TRAIN_EXE=D:/Projects/Niyah.Engine/build-cuda86/MinSizeRel/niyah-train.exe" "-DNIYAH_TRAIN_TOK=D:/Projects/Niyah.Engine/build-cuda86/niyah_train_fixture.tok" "-DNIYAH_TRAIN_SHARD=D:/Projects/Niyah.Engine/build-cuda86/niyah_train_fixture.srd" "-DNIYAH_TRAIN_SHARD_ALT=D:/Projects/Niyah.Engine/build-cuda86/niyah_train_fixture_alt.srd" "-DNIYAH_TRAIN_CKPT=D:/Projects/Niyah.Engine/build-cuda86/niyah_train_fixture_3.ckpt" "-DNIYAH_TRAIN_CUR=D:/Projects/Niyah.Engine/build-cuda86/niyah_train_fixture_3.cursor" "-P" "D:/Projects/Niyah.Engine/tests/check_train_resume_mismatch.cmake")
  set_tests_properties("niyah_train_resume_dataset_mismatch_test" PROPERTIES  FIXTURES_REQUIRED "niyah_train_files" _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;538;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("niyah_train_resume_dataset_mismatch_test" "C:/Program Files/CMake/bin/cmake.exe" "-DNIYAH_TRAIN_EXE=D:/Projects/Niyah.Engine/build-cuda86/RelWithDebInfo/niyah-train.exe" "-DNIYAH_TRAIN_TOK=D:/Projects/Niyah.Engine/build-cuda86/niyah_train_fixture.tok" "-DNIYAH_TRAIN_SHARD=D:/Projects/Niyah.Engine/build-cuda86/niyah_train_fixture.srd" "-DNIYAH_TRAIN_SHARD_ALT=D:/Projects/Niyah.Engine/build-cuda86/niyah_train_fixture_alt.srd" "-DNIYAH_TRAIN_CKPT=D:/Projects/Niyah.Engine/build-cuda86/niyah_train_fixture_3.ckpt" "-DNIYAH_TRAIN_CUR=D:/Projects/Niyah.Engine/build-cuda86/niyah_train_fixture_3.cursor" "-P" "D:/Projects/Niyah.Engine/tests/check_train_resume_mismatch.cmake")
  set_tests_properties("niyah_train_resume_dataset_mismatch_test" PROPERTIES  FIXTURES_REQUIRED "niyah_train_files" _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;538;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
else()
  add_test("niyah_train_resume_dataset_mismatch_test" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("niyah_train_multishard_test" "C:/Program Files/CMake/bin/cmake.exe" "-DNIYAH_TRAIN_EXE=D:/Projects/Niyah.Engine/build-cuda86/Debug/niyah-train.exe" "-DNIYAH_TRAIN_TOK=D:/Projects/Niyah.Engine/build-cuda86/niyah_train_fixture.tok" "-DNIYAH_TRAIN_SHARD_A=D:/Projects/Niyah.Engine/build-cuda86/niyah_train_fixture.srd" "-DNIYAH_TRAIN_SHARD_B=D:/Projects/Niyah.Engine/build-cuda86/niyah_train_fixture_alt.srd" "-DNIYAH_TRAIN_MULTI_PREFIX=D:/Projects/Niyah.Engine/build-cuda86/niyah_train_multishard" "-P" "D:/Projects/Niyah.Engine/tests/check_train_multishard.cmake")
  set_tests_properties("niyah_train_multishard_test" PROPERTIES  FIXTURES_REQUIRED "niyah_train_files" _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;550;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("niyah_train_multishard_test" "C:/Program Files/CMake/bin/cmake.exe" "-DNIYAH_TRAIN_EXE=D:/Projects/Niyah.Engine/build-cuda86/Release/niyah-train.exe" "-DNIYAH_TRAIN_TOK=D:/Projects/Niyah.Engine/build-cuda86/niyah_train_fixture.tok" "-DNIYAH_TRAIN_SHARD_A=D:/Projects/Niyah.Engine/build-cuda86/niyah_train_fixture.srd" "-DNIYAH_TRAIN_SHARD_B=D:/Projects/Niyah.Engine/build-cuda86/niyah_train_fixture_alt.srd" "-DNIYAH_TRAIN_MULTI_PREFIX=D:/Projects/Niyah.Engine/build-cuda86/niyah_train_multishard" "-P" "D:/Projects/Niyah.Engine/tests/check_train_multishard.cmake")
  set_tests_properties("niyah_train_multishard_test" PROPERTIES  FIXTURES_REQUIRED "niyah_train_files" _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;550;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test("niyah_train_multishard_test" "C:/Program Files/CMake/bin/cmake.exe" "-DNIYAH_TRAIN_EXE=D:/Projects/Niyah.Engine/build-cuda86/MinSizeRel/niyah-train.exe" "-DNIYAH_TRAIN_TOK=D:/Projects/Niyah.Engine/build-cuda86/niyah_train_fixture.tok" "-DNIYAH_TRAIN_SHARD_A=D:/Projects/Niyah.Engine/build-cuda86/niyah_train_fixture.srd" "-DNIYAH_TRAIN_SHARD_B=D:/Projects/Niyah.Engine/build-cuda86/niyah_train_fixture_alt.srd" "-DNIYAH_TRAIN_MULTI_PREFIX=D:/Projects/Niyah.Engine/build-cuda86/niyah_train_multishard" "-P" "D:/Projects/Niyah.Engine/tests/check_train_multishard.cmake")
  set_tests_properties("niyah_train_multishard_test" PROPERTIES  FIXTURES_REQUIRED "niyah_train_files" _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;550;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("niyah_train_multishard_test" "C:/Program Files/CMake/bin/cmake.exe" "-DNIYAH_TRAIN_EXE=D:/Projects/Niyah.Engine/build-cuda86/RelWithDebInfo/niyah-train.exe" "-DNIYAH_TRAIN_TOK=D:/Projects/Niyah.Engine/build-cuda86/niyah_train_fixture.tok" "-DNIYAH_TRAIN_SHARD_A=D:/Projects/Niyah.Engine/build-cuda86/niyah_train_fixture.srd" "-DNIYAH_TRAIN_SHARD_B=D:/Projects/Niyah.Engine/build-cuda86/niyah_train_fixture_alt.srd" "-DNIYAH_TRAIN_MULTI_PREFIX=D:/Projects/Niyah.Engine/build-cuda86/niyah_train_multishard" "-P" "D:/Projects/Niyah.Engine/tests/check_train_multishard.cmake")
  set_tests_properties("niyah_train_multishard_test" PROPERTIES  FIXTURES_REQUIRED "niyah_train_files" _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;550;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
else()
  add_test("niyah_train_multishard_test" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("niyah_train_pair_mismatch_test" "C:/Program Files/CMake/bin/cmake.exe" "-DNIYAH_TRAIN_EXE=D:/Projects/Niyah.Engine/build-cuda86/Debug/niyah-train.exe" "-DNIYAH_TRAIN_TOK=D:/Projects/Niyah.Engine/build-cuda86/niyah_train_fixture.tok" "-DNIYAH_TRAIN_SHARD=D:/Projects/Niyah.Engine/build-cuda86/niyah_train_fixture.srd" "-DNIYAH_TRAIN_PAIR_PREFIX=D:/Projects/Niyah.Engine/build-cuda86/niyah_train_pair" "-P" "D:/Projects/Niyah.Engine/tests/check_train_pair_mismatch.cmake")
  set_tests_properties("niyah_train_pair_mismatch_test" PROPERTIES  FIXTURES_REQUIRED "niyah_train_files" _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;561;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("niyah_train_pair_mismatch_test" "C:/Program Files/CMake/bin/cmake.exe" "-DNIYAH_TRAIN_EXE=D:/Projects/Niyah.Engine/build-cuda86/Release/niyah-train.exe" "-DNIYAH_TRAIN_TOK=D:/Projects/Niyah.Engine/build-cuda86/niyah_train_fixture.tok" "-DNIYAH_TRAIN_SHARD=D:/Projects/Niyah.Engine/build-cuda86/niyah_train_fixture.srd" "-DNIYAH_TRAIN_PAIR_PREFIX=D:/Projects/Niyah.Engine/build-cuda86/niyah_train_pair" "-P" "D:/Projects/Niyah.Engine/tests/check_train_pair_mismatch.cmake")
  set_tests_properties("niyah_train_pair_mismatch_test" PROPERTIES  FIXTURES_REQUIRED "niyah_train_files" _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;561;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test("niyah_train_pair_mismatch_test" "C:/Program Files/CMake/bin/cmake.exe" "-DNIYAH_TRAIN_EXE=D:/Projects/Niyah.Engine/build-cuda86/MinSizeRel/niyah-train.exe" "-DNIYAH_TRAIN_TOK=D:/Projects/Niyah.Engine/build-cuda86/niyah_train_fixture.tok" "-DNIYAH_TRAIN_SHARD=D:/Projects/Niyah.Engine/build-cuda86/niyah_train_fixture.srd" "-DNIYAH_TRAIN_PAIR_PREFIX=D:/Projects/Niyah.Engine/build-cuda86/niyah_train_pair" "-P" "D:/Projects/Niyah.Engine/tests/check_train_pair_mismatch.cmake")
  set_tests_properties("niyah_train_pair_mismatch_test" PROPERTIES  FIXTURES_REQUIRED "niyah_train_files" _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;561;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("niyah_train_pair_mismatch_test" "C:/Program Files/CMake/bin/cmake.exe" "-DNIYAH_TRAIN_EXE=D:/Projects/Niyah.Engine/build-cuda86/RelWithDebInfo/niyah-train.exe" "-DNIYAH_TRAIN_TOK=D:/Projects/Niyah.Engine/build-cuda86/niyah_train_fixture.tok" "-DNIYAH_TRAIN_SHARD=D:/Projects/Niyah.Engine/build-cuda86/niyah_train_fixture.srd" "-DNIYAH_TRAIN_PAIR_PREFIX=D:/Projects/Niyah.Engine/build-cuda86/niyah_train_pair" "-P" "D:/Projects/Niyah.Engine/tests/check_train_pair_mismatch.cmake")
  set_tests_properties("niyah_train_pair_mismatch_test" PROPERTIES  FIXTURES_REQUIRED "niyah_train_files" _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;561;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
else()
  add_test("niyah_train_pair_mismatch_test" NOT_AVAILABLE)
endif()
