# CMake generated Testfile for 
# Source directory: /workspace/Niyah.Engine/native
# Build directory: /workspace/Niyah.Engine/native/build_linux
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(test_niyah_core "/workspace/Niyah.Engine/native/build_linux/test_niyah_core")
set_tests_properties(test_niyah_core PROPERTIES  _BACKTRACE_TRIPLES "/workspace/Niyah.Engine/native/CMakeLists.txt;123;add_test;/workspace/Niyah.Engine/native/CMakeLists.txt;0;")
add_test(niyah_attention_test "/workspace/Niyah.Engine/native/build_linux/niyah_attention_test")
set_tests_properties(niyah_attention_test PROPERTIES  _BACKTRACE_TRIPLES "/workspace/Niyah.Engine/native/CMakeLists.txt;124;add_test;/workspace/Niyah.Engine/native/CMakeLists.txt;0;")
add_test(niyah_bridge_test "/workspace/Niyah.Engine/native/build_linux/niyah_bridge_test")
set_tests_properties(niyah_bridge_test PROPERTIES  _BACKTRACE_TRIPLES "/workspace/Niyah.Engine/native/CMakeLists.txt;125;add_test;/workspace/Niyah.Engine/native/CMakeLists.txt;0;")
add_test(niyah_embedding_test "/workspace/Niyah.Engine/native/build_linux/niyah_embedding_test")
set_tests_properties(niyah_embedding_test PROPERTIES  _BACKTRACE_TRIPLES "/workspace/Niyah.Engine/native/CMakeLists.txt;126;add_test;/workspace/Niyah.Engine/native/CMakeLists.txt;0;")
add_test(niyah_graph_test "/workspace/Niyah.Engine/native/build_linux/niyah_graph_test")
set_tests_properties(niyah_graph_test PROPERTIES  _BACKTRACE_TRIPLES "/workspace/Niyah.Engine/native/CMakeLists.txt;127;add_test;/workspace/Niyah.Engine/native/CMakeLists.txt;0;")
add_test(niyah_llm_test "/workspace/Niyah.Engine/native/build_linux/niyah_llm_test")
set_tests_properties(niyah_llm_test PROPERTIES  _BACKTRACE_TRIPLES "/workspace/Niyah.Engine/native/CMakeLists.txt;128;add_test;/workspace/Niyah.Engine/native/CMakeLists.txt;0;")
add_test(niyah_llm_generation_test "/workspace/Niyah.Engine/native/build_linux/niyah_llm_generation_test")
set_tests_properties(niyah_llm_generation_test PROPERTIES  _BACKTRACE_TRIPLES "/workspace/Niyah.Engine/native/CMakeLists.txt;129;add_test;/workspace/Niyah.Engine/native/CMakeLists.txt;0;")
add_test(niyah_matmul_test "/workspace/Niyah.Engine/native/build_linux/niyah_matmul_test")
set_tests_properties(niyah_matmul_test PROPERTIES  _BACKTRACE_TRIPLES "/workspace/Niyah.Engine/native/CMakeLists.txt;130;add_test;/workspace/Niyah.Engine/native/CMakeLists.txt;0;")
add_test(niyah_rmsnorm_test "/workspace/Niyah.Engine/native/build_linux/niyah_rmsnorm_test")
set_tests_properties(niyah_rmsnorm_test PROPERTIES  _BACKTRACE_TRIPLES "/workspace/Niyah.Engine/native/CMakeLists.txt;131;add_test;/workspace/Niyah.Engine/native/CMakeLists.txt;0;")
add_test(niyah_rope_test "/workspace/Niyah.Engine/native/build_linux/niyah_rope_test")
set_tests_properties(niyah_rope_test PROPERTIES  _BACKTRACE_TRIPLES "/workspace/Niyah.Engine/native/CMakeLists.txt;132;add_test;/workspace/Niyah.Engine/native/CMakeLists.txt;0;")
add_test(niyah_runtime_test "/workspace/Niyah.Engine/native/build_linux/niyah_runtime_test")
set_tests_properties(niyah_runtime_test PROPERTIES  _BACKTRACE_TRIPLES "/workspace/Niyah.Engine/native/CMakeLists.txt;133;add_test;/workspace/Niyah.Engine/native/CMakeLists.txt;0;")
add_test(niyah_sampler_test "/workspace/Niyah.Engine/native/build_linux/niyah_sampler_test")
set_tests_properties(niyah_sampler_test PROPERTIES  _BACKTRACE_TRIPLES "/workspace/Niyah.Engine/native/CMakeLists.txt;134;add_test;/workspace/Niyah.Engine/native/CMakeLists.txt;0;")
add_test(niyah_softmax_test "/workspace/Niyah.Engine/native/build_linux/niyah_softmax_test")
set_tests_properties(niyah_softmax_test PROPERTIES  _BACKTRACE_TRIPLES "/workspace/Niyah.Engine/native/CMakeLists.txt;135;add_test;/workspace/Niyah.Engine/native/CMakeLists.txt;0;")
add_test(niyah_storage_test "/workspace/Niyah.Engine/native/build_linux/niyah_storage_test")
set_tests_properties(niyah_storage_test PROPERTIES  _BACKTRACE_TRIPLES "/workspace/Niyah.Engine/native/CMakeLists.txt;136;add_test;/workspace/Niyah.Engine/native/CMakeLists.txt;0;")
add_test(niyah_swiglu_test "/workspace/Niyah.Engine/native/build_linux/niyah_swiglu_test")
set_tests_properties(niyah_swiglu_test PROPERTIES  _BACKTRACE_TRIPLES "/workspace/Niyah.Engine/native/CMakeLists.txt;137;add_test;/workspace/Niyah.Engine/native/CMakeLists.txt;0;")
add_test(niyah_telemetry_test "/workspace/Niyah.Engine/native/build_linux/niyah_telemetry_test")
set_tests_properties(niyah_telemetry_test PROPERTIES  _BACKTRACE_TRIPLES "/workspace/Niyah.Engine/native/CMakeLists.txt;138;add_test;/workspace/Niyah.Engine/native/CMakeLists.txt;0;")
add_test(niyah_tokenizer_test "/workspace/Niyah.Engine/native/build_linux/niyah_tokenizer_test")
set_tests_properties(niyah_tokenizer_test PROPERTIES  _BACKTRACE_TRIPLES "/workspace/Niyah.Engine/native/CMakeLists.txt;139;add_test;/workspace/Niyah.Engine/native/CMakeLists.txt;0;")
add_test(niyah_transformer_layer_test "/workspace/Niyah.Engine/native/build_linux/niyah_transformer_layer_test")
set_tests_properties(niyah_transformer_layer_test PROPERTIES  _BACKTRACE_TRIPLES "/workspace/Niyah.Engine/native/CMakeLists.txt;140;add_test;/workspace/Niyah.Engine/native/CMakeLists.txt;0;")
add_test(niyah_search_test "/workspace/Niyah.Engine/native/build_linux/niyah_search_test")
set_tests_properties(niyah_search_test PROPERTIES  _BACKTRACE_TRIPLES "/workspace/Niyah.Engine/native/CMakeLists.txt;141;add_test;/workspace/Niyah.Engine/native/CMakeLists.txt;0;")
add_test(niyah_crawler_test "/workspace/Niyah.Engine/native/build_linux/niyah_crawler_test")
set_tests_properties(niyah_crawler_test PROPERTIES  _BACKTRACE_TRIPLES "/workspace/Niyah.Engine/native/CMakeLists.txt;142;add_test;/workspace/Niyah.Engine/native/CMakeLists.txt;0;")
