#include "niyah_llm.h"
#include "niyah_tokenizer.h"
#include "niyah_sampler.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <assert.h>

/* ============================================================================
 * Helper: Load weights from binary file
 * ============================================================================ */

static uint8_t *load_file(const char *path, size_t *out_size) {
    FILE *f = fopen(path, "rb");
    if (!f) {
        return NULL;
    }

    fseek(f, 0, SEEK_END);
    long size = ftell(f);
    fseek(f, 0, SEEK_SET);

    uint8_t *buffer = malloc(size);
    if (!buffer) {
        fclose(f);
        return NULL;
    }

    size_t read = fread(buffer, 1, size, f);
    fclose(f);

    if (read != (size_t)size) {
        free(buffer);
        return NULL;
    }

    *out_size = size;
    return buffer;
}

/* ============================================================================
 * Test: Generation with real weights
 * ============================================================================ */

static void test_generation_with_weights(void) {
    printf("=== Test: Generation with real weights ===\n");

    /* Load config */
    NiyahLlmConfig config;
    memset(&config, 0, sizeof(config));
    
    /* TODO: Load from config.json (generated by gguf_to_niyah.py) */
    /* For now, use legacy-model-2.5-0.5B defaults */
    config.vocab_size = 151936;
    config.context_size = 2048;
    config.dim = 896;
    config.hidden_dim = 4864;
    config.layer_count = 24;
    config.heads = 14;
    config.kv_heads = 2;
    config.eos_token = 151643;

    /* Validate config */
    assert(niyah_llm_config_validate(&config));
    printf("Config validated\n");

    /* Load weights */
    size_t weights_size = 0;
    uint8_t *weights_buffer = load_file("../weights/legacy-model-2.5-0.5b-f32.bin", &weights_size);
    if (!weights_buffer) {
        printf("SKIP: Weights file not found (run tools/download_and_convert.sh first)\n");
        return;
    }
    printf("Loaded %zu bytes of weights\n", weights_size);

    NiyahLlmModelWeights weights;
    memset(&weights, 0, sizeof(weights));

    bool loaded = niyah_llm_weights_load_from_buffer(&weights, &config, weights_buffer, weights_size);
    assert(loaded);
    printf("Weights loaded\n");

    /* Initialize tokenizer */
    NiyahTokenizer tokenizer;
    niyah_tokenizer_init(&tokenizer, "../models/tokenizer.json");

    /* Tokenize prompt */
    const char *prompt = "Hello, my name is";
    uint32_t tokens[256];
    size_t token_count = 0;
    niyah_tokenizer_encode(&tokenizer, prompt, tokens, &token_count, 256);
    printf("Tokenized prompt: \"%s\" -> %zu tokens\n", prompt, token_count);

    /* Initialize generation */
    NiyahLlmGenerationState *state = niyah_llm_generation_init(
        &config,
        &weights,
        tokens[0],
        100,  /* max_tokens */
        10000.0f,  /* rope_theta */
        0.8f,      /* temperature */
        0.95f,     /* top_p */
        40         /* top_k */
    );
    assert(state);
    printf("Generation initialized\n");

    /* Generate tokens */
    printf("Generating...\n");
    for (size_t i = 0; i < 20; ++i) {
        uint32_t next_token;
        float probability;

        if (!niyah_llm_generation_step(state, &next_token, &probability)) {
            printf("Generation finished at token %zu\n", i);
            break;
        }

        /* Decode token */
        char decoded[256] = {0};
        niyah_tokenizer_decode(&tokenizer, &next_token, 1, decoded, sizeof(decoded));
        printf("  [%zu] token=%u, prob=%.4f, text=\"%s\"\n", 
               i, next_token, probability, decoded);
    }

    /* Cleanup */
    niyah_llm_generation_free(state);
    niyah_tokenizer_free(&tokenizer);
    niyah_llm_weights_unload(&weights);
    free(weights_buffer);

    printf("=== Test passed ===\n\n");
}

/* ============================================================================
 * Main
 * ============================================================================ */

int main(void) {
    test_generation_with_weights();
    return 0;
}
