# CMake generated Testfile for 
# Source directory: D:/Projects/Niyah.Engine
# Build directory: D:/Projects/Niyah.Engine/build-warmup-final-seal
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("niyah_cli_help_test" "D:/Projects/Niyah.Engine/build-warmup-final-seal/Debug/niyah.exe" "--help")
  set_tests_properties("niyah_cli_help_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;177;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("niyah_cli_help_test" "D:/Projects/Niyah.Engine/build-warmup-final-seal/Release/niyah.exe" "--help")
  set_tests_properties("niyah_cli_help_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;177;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test("niyah_cli_help_test" "D:/Projects/Niyah.Engine/build-warmup-final-seal/MinSizeRel/niyah.exe" "--help")
  set_tests_properties("niyah_cli_help_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;177;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("niyah_cli_help_test" "D:/Projects/Niyah.Engine/build-warmup-final-seal/RelWithDebInfo/niyah.exe" "--help")
  set_tests_properties("niyah_cli_help_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;177;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
else()
  add_test("niyah_cli_help_test" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("niyah_cli_prepare_test" "C:/Program Files/CMake/bin/cmake.exe" "-DNIYAH_CLI=D:/Projects/Niyah.Engine/build-warmup-final-seal/Debug/niyah.exe" "-DNIYAH_TRAIN=D:/Projects/Niyah.Engine/build-warmup-final-seal/Debug/niyah-train.exe" "-DWORK_DIR=D:/Projects/Niyah.Engine/build-warmup-final-seal" "-P" "D:/Projects/Niyah.Engine/tests/check_niyah_prepare.cmake")
  set_tests_properties("niyah_cli_prepare_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;180;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("niyah_cli_prepare_test" "C:/Program Files/CMake/bin/cmake.exe" "-DNIYAH_CLI=D:/Projects/Niyah.Engine/build-warmup-final-seal/Release/niyah.exe" "-DNIYAH_TRAIN=D:/Projects/Niyah.Engine/build-warmup-final-seal/Release/niyah-train.exe" "-DWORK_DIR=D:/Projects/Niyah.Engine/build-warmup-final-seal" "-P" "D:/Projects/Niyah.Engine/tests/check_niyah_prepare.cmake")
  set_tests_properties("niyah_cli_prepare_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;180;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test("niyah_cli_prepare_test" "C:/Program Files/CMake/bin/cmake.exe" "-DNIYAH_CLI=D:/Projects/Niyah.Engine/build-warmup-final-seal/MinSizeRel/niyah.exe" "-DNIYAH_TRAIN=D:/Projects/Niyah.Engine/build-warmup-final-seal/MinSizeRel/niyah-train.exe" "-DWORK_DIR=D:/Projects/Niyah.Engine/build-warmup-final-seal" "-P" "D:/Projects/Niyah.Engine/tests/check_niyah_prepare.cmake")
  set_tests_properties("niyah_cli_prepare_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;180;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("niyah_cli_prepare_test" "C:/Program Files/CMake/bin/cmake.exe" "-DNIYAH_CLI=D:/Projects/Niyah.Engine/build-warmup-final-seal/RelWithDebInfo/niyah.exe" "-DNIYAH_TRAIN=D:/Projects/Niyah.Engine/build-warmup-final-seal/RelWithDebInfo/niyah-train.exe" "-DWORK_DIR=D:/Projects/Niyah.Engine/build-warmup-final-seal" "-P" "D:/Projects/Niyah.Engine/tests/check_niyah_prepare.cmake")
  set_tests_properties("niyah_cli_prepare_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;180;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
else()
  add_test("niyah_cli_prepare_test" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("niyah_model_test" "D:/Projects/Niyah.Engine/build-warmup-final-seal/Debug/niyah_model_test.exe")
  set_tests_properties("niyah_model_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;441;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("niyah_model_test" "D:/Projects/Niyah.Engine/build-warmup-final-seal/Release/niyah_model_test.exe")
  set_tests_properties("niyah_model_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;441;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test("niyah_model_test" "D:/Projects/Niyah.Engine/build-warmup-final-seal/MinSizeRel/niyah_model_test.exe")
  set_tests_properties("niyah_model_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;441;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("niyah_model_test" "D:/Projects/Niyah.Engine/build-warmup-final-seal/RelWithDebInfo/niyah_model_test.exe")
  set_tests_properties("niyah_model_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;441;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
else()
  add_test("niyah_model_test" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("niyah_tokenizer_test" "D:/Projects/Niyah.Engine/build-warmup-final-seal/Debug/niyah_tokenizer_test.exe")
  set_tests_properties("niyah_tokenizer_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;442;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("niyah_tokenizer_test" "D:/Projects/Niyah.Engine/build-warmup-final-seal/Release/niyah_tokenizer_test.exe")
  set_tests_properties("niyah_tokenizer_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;442;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test("niyah_tokenizer_test" "D:/Projects/Niyah.Engine/build-warmup-final-seal/MinSizeRel/niyah_tokenizer_test.exe")
  set_tests_properties("niyah_tokenizer_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;442;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("niyah_tokenizer_test" "D:/Projects/Niyah.Engine/build-warmup-final-seal/RelWithDebInfo/niyah_tokenizer_test.exe")
  set_tests_properties("niyah_tokenizer_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;442;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
else()
  add_test("niyah_tokenizer_test" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("niyah_dataset_test" "D:/Projects/Niyah.Engine/build-warmup-final-seal/Debug/niyah_dataset_test.exe")
  set_tests_properties("niyah_dataset_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;443;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("niyah_dataset_test" "D:/Projects/Niyah.Engine/build-warmup-final-seal/Release/niyah_dataset_test.exe")
  set_tests_properties("niyah_dataset_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;443;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test("niyah_dataset_test" "D:/Projects/Niyah.Engine/build-warmup-final-seal/MinSizeRel/niyah_dataset_test.exe")
  set_tests_properties("niyah_dataset_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;443;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("niyah_dataset_test" "D:/Projects/Niyah.Engine/build-warmup-final-seal/RelWithDebInfo/niyah_dataset_test.exe")
  set_tests_properties("niyah_dataset_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;443;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
else()
  add_test("niyah_dataset_test" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("niyah_dataset_shard_test" "D:/Projects/Niyah.Engine/build-warmup-final-seal/Debug/niyah_dataset_shard_test.exe")
  set_tests_properties("niyah_dataset_shard_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;444;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("niyah_dataset_shard_test" "D:/Projects/Niyah.Engine/build-warmup-final-seal/Release/niyah_dataset_shard_test.exe")
  set_tests_properties("niyah_dataset_shard_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;444;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test("niyah_dataset_shard_test" "D:/Projects/Niyah.Engine/build-warmup-final-seal/MinSizeRel/niyah_dataset_shard_test.exe")
  set_tests_properties("niyah_dataset_shard_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;444;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("niyah_dataset_shard_test" "D:/Projects/Niyah.Engine/build-warmup-final-seal/RelWithDebInfo/niyah_dataset_shard_test.exe")
  set_tests_properties("niyah_dataset_shard_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;444;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
else()
  add_test("niyah_dataset_shard_test" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("niyah_dataset_collection_test" "D:/Projects/Niyah.Engine/build-warmup-final-seal/Debug/niyah_dataset_collection_test.exe")
  set_tests_properties("niyah_dataset_collection_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;445;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("niyah_dataset_collection_test" "D:/Projects/Niyah.Engine/build-warmup-final-seal/Release/niyah_dataset_collection_test.exe")
  set_tests_properties("niyah_dataset_collection_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;445;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test("niyah_dataset_collection_test" "D:/Projects/Niyah.Engine/build-warmup-final-seal/MinSizeRel/niyah_dataset_collection_test.exe")
  set_tests_properties("niyah_dataset_collection_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;445;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("niyah_dataset_collection_test" "D:/Projects/Niyah.Engine/build-warmup-final-seal/RelWithDebInfo/niyah_dataset_collection_test.exe")
  set_tests_properties("niyah_dataset_collection_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;445;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
else()
  add_test("niyah_dataset_collection_test" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("niyah_transformer_test" "D:/Projects/Niyah.Engine/build-warmup-final-seal/Debug/niyah_transformer_test.exe")
  set_tests_properties("niyah_transformer_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;446;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("niyah_transformer_test" "D:/Projects/Niyah.Engine/build-warmup-final-seal/Release/niyah_transformer_test.exe")
  set_tests_properties("niyah_transformer_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;446;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test("niyah_transformer_test" "D:/Projects/Niyah.Engine/build-warmup-final-seal/MinSizeRel/niyah_transformer_test.exe")
  set_tests_properties("niyah_transformer_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;446;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("niyah_transformer_test" "D:/Projects/Niyah.Engine/build-warmup-final-seal/RelWithDebInfo/niyah_transformer_test.exe")
  set_tests_properties("niyah_transformer_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;446;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
else()
  add_test("niyah_transformer_test" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("niyah_decode_test" "D:/Projects/Niyah.Engine/build-warmup-final-seal/Debug/niyah_decode_test.exe")
  set_tests_properties("niyah_decode_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;447;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("niyah_decode_test" "D:/Projects/Niyah.Engine/build-warmup-final-seal/Release/niyah_decode_test.exe")
  set_tests_properties("niyah_decode_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;447;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test("niyah_decode_test" "D:/Projects/Niyah.Engine/build-warmup-final-seal/MinSizeRel/niyah_decode_test.exe")
  set_tests_properties("niyah_decode_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;447;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("niyah_decode_test" "D:/Projects/Niyah.Engine/build-warmup-final-seal/RelWithDebInfo/niyah_decode_test.exe")
  set_tests_properties("niyah_decode_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;447;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
else()
  add_test("niyah_decode_test" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("niyah_generation_test" "D:/Projects/Niyah.Engine/build-warmup-final-seal/Debug/niyah_generation_test.exe")
  set_tests_properties("niyah_generation_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;448;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("niyah_generation_test" "D:/Projects/Niyah.Engine/build-warmup-final-seal/Release/niyah_generation_test.exe")
  set_tests_properties("niyah_generation_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;448;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test("niyah_generation_test" "D:/Projects/Niyah.Engine/build-warmup-final-seal/MinSizeRel/niyah_generation_test.exe")
  set_tests_properties("niyah_generation_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;448;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("niyah_generation_test" "D:/Projects/Niyah.Engine/build-warmup-final-seal/RelWithDebInfo/niyah_generation_test.exe")
  set_tests_properties("niyah_generation_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;448;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
else()
  add_test("niyah_generation_test" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("niyah_train_test" "D:/Projects/Niyah.Engine/build-warmup-final-seal/Debug/niyah_train_test.exe")
  set_tests_properties("niyah_train_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;449;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("niyah_train_test" "D:/Projects/Niyah.Engine/build-warmup-final-seal/Release/niyah_train_test.exe")
  set_tests_properties("niyah_train_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;449;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test("niyah_train_test" "D:/Projects/Niyah.Engine/build-warmup-final-seal/MinSizeRel/niyah_train_test.exe")
  set_tests_properties("niyah_train_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;449;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("niyah_train_test" "D:/Projects/Niyah.Engine/build-warmup-final-seal/RelWithDebInfo/niyah_train_test.exe")
  set_tests_properties("niyah_train_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;449;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
else()
  add_test("niyah_train_test" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("niyah_eval_test" "D:/Projects/Niyah.Engine/build-warmup-final-seal/Debug/niyah_eval_test.exe")
  set_tests_properties("niyah_eval_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;450;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("niyah_eval_test" "D:/Projects/Niyah.Engine/build-warmup-final-seal/Release/niyah_eval_test.exe")
  set_tests_properties("niyah_eval_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;450;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test("niyah_eval_test" "D:/Projects/Niyah.Engine/build-warmup-final-seal/MinSizeRel/niyah_eval_test.exe")
  set_tests_properties("niyah_eval_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;450;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("niyah_eval_test" "D:/Projects/Niyah.Engine/build-warmup-final-seal/RelWithDebInfo/niyah_eval_test.exe")
  set_tests_properties("niyah_eval_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;450;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
else()
  add_test("niyah_eval_test" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("niyah_baseline_test" "D:/Projects/Niyah.Engine/build-warmup-final-seal/Debug/niyah_baseline_test.exe")
  set_tests_properties("niyah_baseline_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;451;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("niyah_baseline_test" "D:/Projects/Niyah.Engine/build-warmup-final-seal/Release/niyah_baseline_test.exe")
  set_tests_properties("niyah_baseline_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;451;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test("niyah_baseline_test" "D:/Projects/Niyah.Engine/build-warmup-final-seal/MinSizeRel/niyah_baseline_test.exe")
  set_tests_properties("niyah_baseline_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;451;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("niyah_baseline_test" "D:/Projects/Niyah.Engine/build-warmup-final-seal/RelWithDebInfo/niyah_baseline_test.exe")
  set_tests_properties("niyah_baseline_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;451;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
else()
  add_test("niyah_baseline_test" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("niyah_training_loop_test" "D:/Projects/Niyah.Engine/build-warmup-final-seal/Debug/niyah_training_loop_test.exe")
  set_tests_properties("niyah_training_loop_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;452;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("niyah_training_loop_test" "D:/Projects/Niyah.Engine/build-warmup-final-seal/Release/niyah_training_loop_test.exe")
  set_tests_properties("niyah_training_loop_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;452;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test("niyah_training_loop_test" "D:/Projects/Niyah.Engine/build-warmup-final-seal/MinSizeRel/niyah_training_loop_test.exe")
  set_tests_properties("niyah_training_loop_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;452;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("niyah_training_loop_test" "D:/Projects/Niyah.Engine/build-warmup-final-seal/RelWithDebInfo/niyah_training_loop_test.exe")
  set_tests_properties("niyah_training_loop_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;452;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
else()
  add_test("niyah_training_loop_test" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("niyah_backward_test" "D:/Projects/Niyah.Engine/build-warmup-final-seal/Debug/niyah_backward_test.exe")
  set_tests_properties("niyah_backward_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;453;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("niyah_backward_test" "D:/Projects/Niyah.Engine/build-warmup-final-seal/Release/niyah_backward_test.exe")
  set_tests_properties("niyah_backward_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;453;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test("niyah_backward_test" "D:/Projects/Niyah.Engine/build-warmup-final-seal/MinSizeRel/niyah_backward_test.exe")
  set_tests_properties("niyah_backward_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;453;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("niyah_backward_test" "D:/Projects/Niyah.Engine/build-warmup-final-seal/RelWithDebInfo/niyah_backward_test.exe")
  set_tests_properties("niyah_backward_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;453;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
else()
  add_test("niyah_backward_test" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("niyah_text_pipeline_test" "D:/Projects/Niyah.Engine/build-warmup-final-seal/Debug/niyah_text_pipeline_test.exe")
  set_tests_properties("niyah_text_pipeline_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;454;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("niyah_text_pipeline_test" "D:/Projects/Niyah.Engine/build-warmup-final-seal/Release/niyah_text_pipeline_test.exe")
  set_tests_properties("niyah_text_pipeline_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;454;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test("niyah_text_pipeline_test" "D:/Projects/Niyah.Engine/build-warmup-final-seal/MinSizeRel/niyah_text_pipeline_test.exe")
  set_tests_properties("niyah_text_pipeline_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;454;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("niyah_text_pipeline_test" "D:/Projects/Niyah.Engine/build-warmup-final-seal/RelWithDebInfo/niyah_text_pipeline_test.exe")
  set_tests_properties("niyah_text_pipeline_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;454;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
else()
  add_test("niyah_text_pipeline_test" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("niyah_optimizer_test" "D:/Projects/Niyah.Engine/build-warmup-final-seal/Debug/niyah_optimizer_test.exe")
  set_tests_properties("niyah_optimizer_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;455;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("niyah_optimizer_test" "D:/Projects/Niyah.Engine/build-warmup-final-seal/Release/niyah_optimizer_test.exe")
  set_tests_properties("niyah_optimizer_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;455;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test("niyah_optimizer_test" "D:/Projects/Niyah.Engine/build-warmup-final-seal/MinSizeRel/niyah_optimizer_test.exe")
  set_tests_properties("niyah_optimizer_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;455;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("niyah_optimizer_test" "D:/Projects/Niyah.Engine/build-warmup-final-seal/RelWithDebInfo/niyah_optimizer_test.exe")
  set_tests_properties("niyah_optimizer_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;455;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
else()
  add_test("niyah_optimizer_test" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("niyah_lr_schedule_test" "D:/Projects/Niyah.Engine/build-warmup-final-seal/Debug/niyah_lr_schedule_test.exe")
  set_tests_properties("niyah_lr_schedule_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;456;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("niyah_lr_schedule_test" "D:/Projects/Niyah.Engine/build-warmup-final-seal/Release/niyah_lr_schedule_test.exe")
  set_tests_properties("niyah_lr_schedule_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;456;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test("niyah_lr_schedule_test" "D:/Projects/Niyah.Engine/build-warmup-final-seal/MinSizeRel/niyah_lr_schedule_test.exe")
  set_tests_properties("niyah_lr_schedule_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;456;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("niyah_lr_schedule_test" "D:/Projects/Niyah.Engine/build-warmup-final-seal/RelWithDebInfo/niyah_lr_schedule_test.exe")
  set_tests_properties("niyah_lr_schedule_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;456;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
else()
  add_test("niyah_lr_schedule_test" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("niyah_checkpoint_test" "D:/Projects/Niyah.Engine/build-warmup-final-seal/Debug/niyah_checkpoint_test.exe")
  set_tests_properties("niyah_checkpoint_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;457;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("niyah_checkpoint_test" "D:/Projects/Niyah.Engine/build-warmup-final-seal/Release/niyah_checkpoint_test.exe")
  set_tests_properties("niyah_checkpoint_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;457;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test("niyah_checkpoint_test" "D:/Projects/Niyah.Engine/build-warmup-final-seal/MinSizeRel/niyah_checkpoint_test.exe")
  set_tests_properties("niyah_checkpoint_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;457;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("niyah_checkpoint_test" "D:/Projects/Niyah.Engine/build-warmup-final-seal/RelWithDebInfo/niyah_checkpoint_test.exe")
  set_tests_properties("niyah_checkpoint_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;457;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
else()
  add_test("niyah_checkpoint_test" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("niyah_checkpoint_model_only_test" "D:/Projects/Niyah.Engine/build-warmup-final-seal/Debug/niyah_checkpoint_model_only_test.exe")
  set_tests_properties("niyah_checkpoint_model_only_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;458;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("niyah_checkpoint_model_only_test" "D:/Projects/Niyah.Engine/build-warmup-final-seal/Release/niyah_checkpoint_model_only_test.exe")
  set_tests_properties("niyah_checkpoint_model_only_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;458;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test("niyah_checkpoint_model_only_test" "D:/Projects/Niyah.Engine/build-warmup-final-seal/MinSizeRel/niyah_checkpoint_model_only_test.exe")
  set_tests_properties("niyah_checkpoint_model_only_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;458;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("niyah_checkpoint_model_only_test" "D:/Projects/Niyah.Engine/build-warmup-final-seal/RelWithDebInfo/niyah_checkpoint_model_only_test.exe")
  set_tests_properties("niyah_checkpoint_model_only_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;458;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
else()
  add_test("niyah_checkpoint_model_only_test" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("niyah_segment_embeddings_test" "D:/Projects/Niyah.Engine/build-warmup-final-seal/Debug/niyah_segment_embeddings_test.exe")
  set_tests_properties("niyah_segment_embeddings_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;459;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("niyah_segment_embeddings_test" "D:/Projects/Niyah.Engine/build-warmup-final-seal/Release/niyah_segment_embeddings_test.exe")
  set_tests_properties("niyah_segment_embeddings_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;459;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test("niyah_segment_embeddings_test" "D:/Projects/Niyah.Engine/build-warmup-final-seal/MinSizeRel/niyah_segment_embeddings_test.exe")
  set_tests_properties("niyah_segment_embeddings_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;459;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("niyah_segment_embeddings_test" "D:/Projects/Niyah.Engine/build-warmup-final-seal/RelWithDebInfo/niyah_segment_embeddings_test.exe")
  set_tests_properties("niyah_segment_embeddings_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;459;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
else()
  add_test("niyah_segment_embeddings_test" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("niyah_train_help_test" "D:/Projects/Niyah.Engine/build-warmup-final-seal/Debug/niyah-train.exe" "--help")
  set_tests_properties("niyah_train_help_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;471;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("niyah_train_help_test" "D:/Projects/Niyah.Engine/build-warmup-final-seal/Release/niyah-train.exe" "--help")
  set_tests_properties("niyah_train_help_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;471;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test("niyah_train_help_test" "D:/Projects/Niyah.Engine/build-warmup-final-seal/MinSizeRel/niyah-train.exe" "--help")
  set_tests_properties("niyah_train_help_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;471;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("niyah_train_help_test" "D:/Projects/Niyah.Engine/build-warmup-final-seal/RelWithDebInfo/niyah-train.exe" "--help")
  set_tests_properties("niyah_train_help_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;471;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
else()
  add_test("niyah_train_help_test" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("niyah_training_fixture_test" "D:/Projects/Niyah.Engine/build-warmup-final-seal/Debug/niyah_training_fixture.exe" "D:/Projects/Niyah.Engine/build-warmup-final-seal/niyah_train_fixture.tok" "D:/Projects/Niyah.Engine/build-warmup-final-seal/niyah_train_fixture.srd" "D:/Projects/Niyah.Engine/build-warmup-final-seal/niyah_train_fixture_alt.srd" "D:/Projects/Niyah.Engine/build-warmup-final-seal/niyah_train_fixture_1.ckpt" "D:/Projects/Niyah.Engine/build-warmup-final-seal/niyah_train_fixture_1.cursor" "D:/Projects/Niyah.Engine/build-warmup-final-seal/niyah_train_fixture_2.ckpt" "D:/Projects/Niyah.Engine/build-warmup-final-seal/niyah_train_fixture_2.cursor")
  set_tests_properties("niyah_training_fixture_test" PROPERTIES  FIXTURES_SETUP "niyah_train_files" _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;473;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("niyah_training_fixture_test" "D:/Projects/Niyah.Engine/build-warmup-final-seal/Release/niyah_training_fixture.exe" "D:/Projects/Niyah.Engine/build-warmup-final-seal/niyah_train_fixture.tok" "D:/Projects/Niyah.Engine/build-warmup-final-seal/niyah_train_fixture.srd" "D:/Projects/Niyah.Engine/build-warmup-final-seal/niyah_train_fixture_alt.srd" "D:/Projects/Niyah.Engine/build-warmup-final-seal/niyah_train_fixture_1.ckpt" "D:/Projects/Niyah.Engine/build-warmup-final-seal/niyah_train_fixture_1.cursor" "D:/Projects/Niyah.Engine/build-warmup-final-seal/niyah_train_fixture_2.ckpt" "D:/Projects/Niyah.Engine/build-warmup-final-seal/niyah_train_fixture_2.cursor")
  set_tests_properties("niyah_training_fixture_test" PROPERTIES  FIXTURES_SETUP "niyah_train_files" _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;473;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test("niyah_training_fixture_test" "D:/Projects/Niyah.Engine/build-warmup-final-seal/MinSizeRel/niyah_training_fixture.exe" "D:/Projects/Niyah.Engine/build-warmup-final-seal/niyah_train_fixture.tok" "D:/Projects/Niyah.Engine/build-warmup-final-seal/niyah_train_fixture.srd" "D:/Projects/Niyah.Engine/build-warmup-final-seal/niyah_train_fixture_alt.srd" "D:/Projects/Niyah.Engine/build-warmup-final-seal/niyah_train_fixture_1.ckpt" "D:/Projects/Niyah.Engine/build-warmup-final-seal/niyah_train_fixture_1.cursor" "D:/Projects/Niyah.Engine/build-warmup-final-seal/niyah_train_fixture_2.ckpt" "D:/Projects/Niyah.Engine/build-warmup-final-seal/niyah_train_fixture_2.cursor")
  set_tests_properties("niyah_training_fixture_test" PROPERTIES  FIXTURES_SETUP "niyah_train_files" _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;473;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("niyah_training_fixture_test" "D:/Projects/Niyah.Engine/build-warmup-final-seal/RelWithDebInfo/niyah_training_fixture.exe" "D:/Projects/Niyah.Engine/build-warmup-final-seal/niyah_train_fixture.tok" "D:/Projects/Niyah.Engine/build-warmup-final-seal/niyah_train_fixture.srd" "D:/Projects/Niyah.Engine/build-warmup-final-seal/niyah_train_fixture_alt.srd" "D:/Projects/Niyah.Engine/build-warmup-final-seal/niyah_train_fixture_1.ckpt" "D:/Projects/Niyah.Engine/build-warmup-final-seal/niyah_train_fixture_1.cursor" "D:/Projects/Niyah.Engine/build-warmup-final-seal/niyah_train_fixture_2.ckpt" "D:/Projects/Niyah.Engine/build-warmup-final-seal/niyah_train_fixture_2.cursor")
  set_tests_properties("niyah_training_fixture_test" PROPERTIES  FIXTURES_SETUP "niyah_train_files" _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;473;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
else()
  add_test("niyah_training_fixture_test" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("niyah_train_new_test" "D:/Projects/Niyah.Engine/build-warmup-final-seal/Debug/niyah-train.exe" "new" "--tokenizer" "D:/Projects/Niyah.Engine/build-warmup-final-seal/niyah_train_fixture.tok" "--shard" "D:/Projects/Niyah.Engine/build-warmup-final-seal/niyah_train_fixture.srd" "--checkpoint-out" "D:/Projects/Niyah.Engine/build-warmup-final-seal/niyah_train_fixture_1.ckpt" "--cursor-out" "D:/Projects/Niyah.Engine/build-warmup-final-seal/niyah_train_fixture_1.cursor" "--updates" "2" "--batch-size" "1" "--accumulation-steps" "1" "--model-seed" "42" "--data-seed" "7" "--context-length" "4" "--embedding-dim" "8" "--layers" "1" "--heads" "2" "--kv-heads" "1" "--ffn-hidden-dim" "16" "--rms-norm-eps" "0.00001" "--tie-word-embeddings" "1" "--learning-rate" "0.001" "--beta1" "0.9" "--beta2" "0.999" "--epsilon" "0.00000001" "--weight-decay" "0.0" "--max-grad-norm" "1.0")
  set_tests_properties("niyah_train_new_test" PROPERTIES  FIXTURES_REQUIRED "niyah_train_files" _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;482;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("niyah_train_new_test" "D:/Projects/Niyah.Engine/build-warmup-final-seal/Release/niyah-train.exe" "new" "--tokenizer" "D:/Projects/Niyah.Engine/build-warmup-final-seal/niyah_train_fixture.tok" "--shard" "D:/Projects/Niyah.Engine/build-warmup-final-seal/niyah_train_fixture.srd" "--checkpoint-out" "D:/Projects/Niyah.Engine/build-warmup-final-seal/niyah_train_fixture_1.ckpt" "--cursor-out" "D:/Projects/Niyah.Engine/build-warmup-final-seal/niyah_train_fixture_1.cursor" "--updates" "2" "--batch-size" "1" "--accumulation-steps" "1" "--model-seed" "42" "--data-seed" "7" "--context-length" "4" "--embedding-dim" "8" "--layers" "1" "--heads" "2" "--kv-heads" "1" "--ffn-hidden-dim" "16" "--rms-norm-eps" "0.00001" "--tie-word-embeddings" "1" "--learning-rate" "0.001" "--beta1" "0.9" "--beta2" "0.999" "--epsilon" "0.00000001" "--weight-decay" "0.0" "--max-grad-norm" "1.0")
  set_tests_properties("niyah_train_new_test" PROPERTIES  FIXTURES_REQUIRED "niyah_train_files" _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;482;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test("niyah_train_new_test" "D:/Projects/Niyah.Engine/build-warmup-final-seal/MinSizeRel/niyah-train.exe" "new" "--tokenizer" "D:/Projects/Niyah.Engine/build-warmup-final-seal/niyah_train_fixture.tok" "--shard" "D:/Projects/Niyah.Engine/build-warmup-final-seal/niyah_train_fixture.srd" "--checkpoint-out" "D:/Projects/Niyah.Engine/build-warmup-final-seal/niyah_train_fixture_1.ckpt" "--cursor-out" "D:/Projects/Niyah.Engine/build-warmup-final-seal/niyah_train_fixture_1.cursor" "--updates" "2" "--batch-size" "1" "--accumulation-steps" "1" "--model-seed" "42" "--data-seed" "7" "--context-length" "4" "--embedding-dim" "8" "--layers" "1" "--heads" "2" "--kv-heads" "1" "--ffn-hidden-dim" "16" "--rms-norm-eps" "0.00001" "--tie-word-embeddings" "1" "--learning-rate" "0.001" "--beta1" "0.9" "--beta2" "0.999" "--epsilon" "0.00000001" "--weight-decay" "0.0" "--max-grad-norm" "1.0")
  set_tests_properties("niyah_train_new_test" PROPERTIES  FIXTURES_REQUIRED "niyah_train_files" _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;482;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("niyah_train_new_test" "D:/Projects/Niyah.Engine/build-warmup-final-seal/RelWithDebInfo/niyah-train.exe" "new" "--tokenizer" "D:/Projects/Niyah.Engine/build-warmup-final-seal/niyah_train_fixture.tok" "--shard" "D:/Projects/Niyah.Engine/build-warmup-final-seal/niyah_train_fixture.srd" "--checkpoint-out" "D:/Projects/Niyah.Engine/build-warmup-final-seal/niyah_train_fixture_1.ckpt" "--cursor-out" "D:/Projects/Niyah.Engine/build-warmup-final-seal/niyah_train_fixture_1.cursor" "--updates" "2" "--batch-size" "1" "--accumulation-steps" "1" "--model-seed" "42" "--data-seed" "7" "--context-length" "4" "--embedding-dim" "8" "--layers" "1" "--heads" "2" "--kv-heads" "1" "--ffn-hidden-dim" "16" "--rms-norm-eps" "0.00001" "--tie-word-embeddings" "1" "--learning-rate" "0.001" "--beta1" "0.9" "--beta2" "0.999" "--epsilon" "0.00000001" "--weight-decay" "0.0" "--max-grad-norm" "1.0")
  set_tests_properties("niyah_train_new_test" PROPERTIES  FIXTURES_REQUIRED "niyah_train_files" _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;482;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
else()
  add_test("niyah_train_new_test" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("niyah_cli_run_test" "C:/Program Files/CMake/bin/cmake.exe" "-DNIYAH_FIXTURE=D:/Projects/Niyah.Engine/build-warmup-final-seal/Debug/niyah_training_fixture.exe" "-DNIYAH_TRAIN=D:/Projects/Niyah.Engine/build-warmup-final-seal/Debug/niyah-train.exe" "-DNIYAH_CLI=D:/Projects/Niyah.Engine/build-warmup-final-seal/Debug/niyah.exe" "-DWORK_DIR=D:/Projects/Niyah.Engine/build-warmup-final-seal" "-DBACKEND=cpu" "-P" "D:/Projects/Niyah.Engine/tests/check_niyah_run.cmake")
  set_tests_properties("niyah_cli_run_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;510;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("niyah_cli_run_test" "C:/Program Files/CMake/bin/cmake.exe" "-DNIYAH_FIXTURE=D:/Projects/Niyah.Engine/build-warmup-final-seal/Release/niyah_training_fixture.exe" "-DNIYAH_TRAIN=D:/Projects/Niyah.Engine/build-warmup-final-seal/Release/niyah-train.exe" "-DNIYAH_CLI=D:/Projects/Niyah.Engine/build-warmup-final-seal/Release/niyah.exe" "-DWORK_DIR=D:/Projects/Niyah.Engine/build-warmup-final-seal" "-DBACKEND=cpu" "-P" "D:/Projects/Niyah.Engine/tests/check_niyah_run.cmake")
  set_tests_properties("niyah_cli_run_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;510;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test("niyah_cli_run_test" "C:/Program Files/CMake/bin/cmake.exe" "-DNIYAH_FIXTURE=D:/Projects/Niyah.Engine/build-warmup-final-seal/MinSizeRel/niyah_training_fixture.exe" "-DNIYAH_TRAIN=D:/Projects/Niyah.Engine/build-warmup-final-seal/MinSizeRel/niyah-train.exe" "-DNIYAH_CLI=D:/Projects/Niyah.Engine/build-warmup-final-seal/MinSizeRel/niyah.exe" "-DWORK_DIR=D:/Projects/Niyah.Engine/build-warmup-final-seal" "-DBACKEND=cpu" "-P" "D:/Projects/Niyah.Engine/tests/check_niyah_run.cmake")
  set_tests_properties("niyah_cli_run_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;510;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("niyah_cli_run_test" "C:/Program Files/CMake/bin/cmake.exe" "-DNIYAH_FIXTURE=D:/Projects/Niyah.Engine/build-warmup-final-seal/RelWithDebInfo/niyah_training_fixture.exe" "-DNIYAH_TRAIN=D:/Projects/Niyah.Engine/build-warmup-final-seal/RelWithDebInfo/niyah-train.exe" "-DNIYAH_CLI=D:/Projects/Niyah.Engine/build-warmup-final-seal/RelWithDebInfo/niyah.exe" "-DWORK_DIR=D:/Projects/Niyah.Engine/build-warmup-final-seal" "-DBACKEND=cpu" "-P" "D:/Projects/Niyah.Engine/tests/check_niyah_run.cmake")
  set_tests_properties("niyah_cli_run_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;510;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
else()
  add_test("niyah_cli_run_test" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("niyah_cli_eval_test" "C:/Program Files/CMake/bin/cmake.exe" "-DNIYAH_FIXTURE=D:/Projects/Niyah.Engine/build-warmup-final-seal/Debug/niyah_training_fixture.exe" "-DNIYAH_TRAIN=D:/Projects/Niyah.Engine/build-warmup-final-seal/Debug/niyah-train.exe" "-DNIYAH_CLI=D:/Projects/Niyah.Engine/build-warmup-final-seal/Debug/niyah.exe" "-DWORK_DIR=D:/Projects/Niyah.Engine/build-warmup-final-seal" "-P" "D:/Projects/Niyah.Engine/tests/check_niyah_eval.cmake")
  set_tests_properties("niyah_cli_eval_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;519;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("niyah_cli_eval_test" "C:/Program Files/CMake/bin/cmake.exe" "-DNIYAH_FIXTURE=D:/Projects/Niyah.Engine/build-warmup-final-seal/Release/niyah_training_fixture.exe" "-DNIYAH_TRAIN=D:/Projects/Niyah.Engine/build-warmup-final-seal/Release/niyah-train.exe" "-DNIYAH_CLI=D:/Projects/Niyah.Engine/build-warmup-final-seal/Release/niyah.exe" "-DWORK_DIR=D:/Projects/Niyah.Engine/build-warmup-final-seal" "-P" "D:/Projects/Niyah.Engine/tests/check_niyah_eval.cmake")
  set_tests_properties("niyah_cli_eval_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;519;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test("niyah_cli_eval_test" "C:/Program Files/CMake/bin/cmake.exe" "-DNIYAH_FIXTURE=D:/Projects/Niyah.Engine/build-warmup-final-seal/MinSizeRel/niyah_training_fixture.exe" "-DNIYAH_TRAIN=D:/Projects/Niyah.Engine/build-warmup-final-seal/MinSizeRel/niyah-train.exe" "-DNIYAH_CLI=D:/Projects/Niyah.Engine/build-warmup-final-seal/MinSizeRel/niyah.exe" "-DWORK_DIR=D:/Projects/Niyah.Engine/build-warmup-final-seal" "-P" "D:/Projects/Niyah.Engine/tests/check_niyah_eval.cmake")
  set_tests_properties("niyah_cli_eval_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;519;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("niyah_cli_eval_test" "C:/Program Files/CMake/bin/cmake.exe" "-DNIYAH_FIXTURE=D:/Projects/Niyah.Engine/build-warmup-final-seal/RelWithDebInfo/niyah_training_fixture.exe" "-DNIYAH_TRAIN=D:/Projects/Niyah.Engine/build-warmup-final-seal/RelWithDebInfo/niyah-train.exe" "-DNIYAH_CLI=D:/Projects/Niyah.Engine/build-warmup-final-seal/RelWithDebInfo/niyah.exe" "-DWORK_DIR=D:/Projects/Niyah.Engine/build-warmup-final-seal" "-P" "D:/Projects/Niyah.Engine/tests/check_niyah_eval.cmake")
  set_tests_properties("niyah_cli_eval_test" PROPERTIES  _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;519;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
else()
  add_test("niyah_cli_eval_test" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("niyah_cli_cuda_unavailable_test" "D:/Projects/Niyah.Engine/build-warmup-final-seal/Debug/niyah.exe" "run" "--tokenizer" "unused" "--checkpoint" "unused" "--prompt" "x" "--max-new-tokens" "1" "--backend" "cuda")
  set_tests_properties("niyah_cli_cuda_unavailable_test" PROPERTIES  WILL_FAIL "TRUE" _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;537;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("niyah_cli_cuda_unavailable_test" "D:/Projects/Niyah.Engine/build-warmup-final-seal/Release/niyah.exe" "run" "--tokenizer" "unused" "--checkpoint" "unused" "--prompt" "x" "--max-new-tokens" "1" "--backend" "cuda")
  set_tests_properties("niyah_cli_cuda_unavailable_test" PROPERTIES  WILL_FAIL "TRUE" _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;537;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test("niyah_cli_cuda_unavailable_test" "D:/Projects/Niyah.Engine/build-warmup-final-seal/MinSizeRel/niyah.exe" "run" "--tokenizer" "unused" "--checkpoint" "unused" "--prompt" "x" "--max-new-tokens" "1" "--backend" "cuda")
  set_tests_properties("niyah_cli_cuda_unavailable_test" PROPERTIES  WILL_FAIL "TRUE" _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;537;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("niyah_cli_cuda_unavailable_test" "D:/Projects/Niyah.Engine/build-warmup-final-seal/RelWithDebInfo/niyah.exe" "run" "--tokenizer" "unused" "--checkpoint" "unused" "--prompt" "x" "--max-new-tokens" "1" "--backend" "cuda")
  set_tests_properties("niyah_cli_cuda_unavailable_test" PROPERTIES  WILL_FAIL "TRUE" _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;537;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
else()
  add_test("niyah_cli_cuda_unavailable_test" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("niyah_train_resume_test" "D:/Projects/Niyah.Engine/build-warmup-final-seal/Debug/niyah-train.exe" "resume" "--tokenizer" "D:/Projects/Niyah.Engine/build-warmup-final-seal/niyah_train_fixture.tok" "--shard" "D:/Projects/Niyah.Engine/build-warmup-final-seal/niyah_train_fixture.srd" "--checkpoint-in" "D:/Projects/Niyah.Engine/build-warmup-final-seal/niyah_train_fixture_1.ckpt" "--cursor-in" "D:/Projects/Niyah.Engine/build-warmup-final-seal/niyah_train_fixture_1.cursor" "--checkpoint-out" "D:/Projects/Niyah.Engine/build-warmup-final-seal/niyah_train_fixture_2.ckpt" "--cursor-out" "D:/Projects/Niyah.Engine/build-warmup-final-seal/niyah_train_fixture_2.cursor" "--updates" "2" "--batch-size" "1" "--accumulation-steps" "1")
  set_tests_properties("niyah_train_resume_test" PROPERTIES  DEPENDS "niyah_train_new_test" FIXTURES_REQUIRED "niyah_train_files" _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;550;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("niyah_train_resume_test" "D:/Projects/Niyah.Engine/build-warmup-final-seal/Release/niyah-train.exe" "resume" "--tokenizer" "D:/Projects/Niyah.Engine/build-warmup-final-seal/niyah_train_fixture.tok" "--shard" "D:/Projects/Niyah.Engine/build-warmup-final-seal/niyah_train_fixture.srd" "--checkpoint-in" "D:/Projects/Niyah.Engine/build-warmup-final-seal/niyah_train_fixture_1.ckpt" "--cursor-in" "D:/Projects/Niyah.Engine/build-warmup-final-seal/niyah_train_fixture_1.cursor" "--checkpoint-out" "D:/Projects/Niyah.Engine/build-warmup-final-seal/niyah_train_fixture_2.ckpt" "--cursor-out" "D:/Projects/Niyah.Engine/build-warmup-final-seal/niyah_train_fixture_2.cursor" "--updates" "2" "--batch-size" "1" "--accumulation-steps" "1")
  set_tests_properties("niyah_train_resume_test" PROPERTIES  DEPENDS "niyah_train_new_test" FIXTURES_REQUIRED "niyah_train_files" _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;550;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test("niyah_train_resume_test" "D:/Projects/Niyah.Engine/build-warmup-final-seal/MinSizeRel/niyah-train.exe" "resume" "--tokenizer" "D:/Projects/Niyah.Engine/build-warmup-final-seal/niyah_train_fixture.tok" "--shard" "D:/Projects/Niyah.Engine/build-warmup-final-seal/niyah_train_fixture.srd" "--checkpoint-in" "D:/Projects/Niyah.Engine/build-warmup-final-seal/niyah_train_fixture_1.ckpt" "--cursor-in" "D:/Projects/Niyah.Engine/build-warmup-final-seal/niyah_train_fixture_1.cursor" "--checkpoint-out" "D:/Projects/Niyah.Engine/build-warmup-final-seal/niyah_train_fixture_2.ckpt" "--cursor-out" "D:/Projects/Niyah.Engine/build-warmup-final-seal/niyah_train_fixture_2.cursor" "--updates" "2" "--batch-size" "1" "--accumulation-steps" "1")
  set_tests_properties("niyah_train_resume_test" PROPERTIES  DEPENDS "niyah_train_new_test" FIXTURES_REQUIRED "niyah_train_files" _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;550;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("niyah_train_resume_test" "D:/Projects/Niyah.Engine/build-warmup-final-seal/RelWithDebInfo/niyah-train.exe" "resume" "--tokenizer" "D:/Projects/Niyah.Engine/build-warmup-final-seal/niyah_train_fixture.tok" "--shard" "D:/Projects/Niyah.Engine/build-warmup-final-seal/niyah_train_fixture.srd" "--checkpoint-in" "D:/Projects/Niyah.Engine/build-warmup-final-seal/niyah_train_fixture_1.ckpt" "--cursor-in" "D:/Projects/Niyah.Engine/build-warmup-final-seal/niyah_train_fixture_1.cursor" "--checkpoint-out" "D:/Projects/Niyah.Engine/build-warmup-final-seal/niyah_train_fixture_2.ckpt" "--cursor-out" "D:/Projects/Niyah.Engine/build-warmup-final-seal/niyah_train_fixture_2.cursor" "--updates" "2" "--batch-size" "1" "--accumulation-steps" "1")
  set_tests_properties("niyah_train_resume_test" PROPERTIES  DEPENDS "niyah_train_new_test" FIXTURES_REQUIRED "niyah_train_files" _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;550;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
else()
  add_test("niyah_train_resume_test" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("niyah_train_resume_equivalence_test" "C:/Program Files/CMake/bin/cmake.exe" "-DNIYAH_TRAIN=D:/Projects/Niyah.Engine/build-warmup-final-seal/Debug/niyah-train.exe" "-DTOKENIZER=D:/Projects/Niyah.Engine/build-warmup-final-seal/niyah_train_fixture.tok" "-DSHARD=D:/Projects/Niyah.Engine/build-warmup-final-seal/niyah_train_fixture.srd" "-DWORK_DIR=D:/Projects/Niyah.Engine/build-warmup-final-seal" "-P" "D:/Projects/Niyah.Engine/tests/check_niyah_train_resume_equivalence.cmake")
  set_tests_properties("niyah_train_resume_equivalence_test" PROPERTIES  FIXTURES_REQUIRED "niyah_train_files" _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;565;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("niyah_train_resume_equivalence_test" "C:/Program Files/CMake/bin/cmake.exe" "-DNIYAH_TRAIN=D:/Projects/Niyah.Engine/build-warmup-final-seal/Release/niyah-train.exe" "-DTOKENIZER=D:/Projects/Niyah.Engine/build-warmup-final-seal/niyah_train_fixture.tok" "-DSHARD=D:/Projects/Niyah.Engine/build-warmup-final-seal/niyah_train_fixture.srd" "-DWORK_DIR=D:/Projects/Niyah.Engine/build-warmup-final-seal" "-P" "D:/Projects/Niyah.Engine/tests/check_niyah_train_resume_equivalence.cmake")
  set_tests_properties("niyah_train_resume_equivalence_test" PROPERTIES  FIXTURES_REQUIRED "niyah_train_files" _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;565;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test("niyah_train_resume_equivalence_test" "C:/Program Files/CMake/bin/cmake.exe" "-DNIYAH_TRAIN=D:/Projects/Niyah.Engine/build-warmup-final-seal/MinSizeRel/niyah-train.exe" "-DTOKENIZER=D:/Projects/Niyah.Engine/build-warmup-final-seal/niyah_train_fixture.tok" "-DSHARD=D:/Projects/Niyah.Engine/build-warmup-final-seal/niyah_train_fixture.srd" "-DWORK_DIR=D:/Projects/Niyah.Engine/build-warmup-final-seal" "-P" "D:/Projects/Niyah.Engine/tests/check_niyah_train_resume_equivalence.cmake")
  set_tests_properties("niyah_train_resume_equivalence_test" PROPERTIES  FIXTURES_REQUIRED "niyah_train_files" _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;565;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("niyah_train_resume_equivalence_test" "C:/Program Files/CMake/bin/cmake.exe" "-DNIYAH_TRAIN=D:/Projects/Niyah.Engine/build-warmup-final-seal/RelWithDebInfo/niyah-train.exe" "-DTOKENIZER=D:/Projects/Niyah.Engine/build-warmup-final-seal/niyah_train_fixture.tok" "-DSHARD=D:/Projects/Niyah.Engine/build-warmup-final-seal/niyah_train_fixture.srd" "-DWORK_DIR=D:/Projects/Niyah.Engine/build-warmup-final-seal" "-P" "D:/Projects/Niyah.Engine/tests/check_niyah_train_resume_equivalence.cmake")
  set_tests_properties("niyah_train_resume_equivalence_test" PROPERTIES  FIXTURES_REQUIRED "niyah_train_files" _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;565;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
else()
  add_test("niyah_train_resume_equivalence_test" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("niyah_train_warmup_contract_test" "C:/Program Files/CMake/bin/cmake.exe" "-DNIYAH_TRAIN=D:/Projects/Niyah.Engine/build-warmup-final-seal/Debug/niyah-train.exe" "-DTOKENIZER=D:/Projects/Niyah.Engine/build-warmup-final-seal/niyah_train_fixture.tok" "-DSHARD=D:/Projects/Niyah.Engine/build-warmup-final-seal/niyah_train_fixture.srd" "-DWORK_DIR=D:/Projects/Niyah.Engine/build-warmup-final-seal" "-P" "D:/Projects/Niyah.Engine/tests/check_niyah_train_warmup_contract.cmake")
  set_tests_properties("niyah_train_warmup_contract_test" PROPERTIES  FIXTURES_REQUIRED "niyah_train_files" _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;575;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("niyah_train_warmup_contract_test" "C:/Program Files/CMake/bin/cmake.exe" "-DNIYAH_TRAIN=D:/Projects/Niyah.Engine/build-warmup-final-seal/Release/niyah-train.exe" "-DTOKENIZER=D:/Projects/Niyah.Engine/build-warmup-final-seal/niyah_train_fixture.tok" "-DSHARD=D:/Projects/Niyah.Engine/build-warmup-final-seal/niyah_train_fixture.srd" "-DWORK_DIR=D:/Projects/Niyah.Engine/build-warmup-final-seal" "-P" "D:/Projects/Niyah.Engine/tests/check_niyah_train_warmup_contract.cmake")
  set_tests_properties("niyah_train_warmup_contract_test" PROPERTIES  FIXTURES_REQUIRED "niyah_train_files" _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;575;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test("niyah_train_warmup_contract_test" "C:/Program Files/CMake/bin/cmake.exe" "-DNIYAH_TRAIN=D:/Projects/Niyah.Engine/build-warmup-final-seal/MinSizeRel/niyah-train.exe" "-DTOKENIZER=D:/Projects/Niyah.Engine/build-warmup-final-seal/niyah_train_fixture.tok" "-DSHARD=D:/Projects/Niyah.Engine/build-warmup-final-seal/niyah_train_fixture.srd" "-DWORK_DIR=D:/Projects/Niyah.Engine/build-warmup-final-seal" "-P" "D:/Projects/Niyah.Engine/tests/check_niyah_train_warmup_contract.cmake")
  set_tests_properties("niyah_train_warmup_contract_test" PROPERTIES  FIXTURES_REQUIRED "niyah_train_files" _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;575;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("niyah_train_warmup_contract_test" "C:/Program Files/CMake/bin/cmake.exe" "-DNIYAH_TRAIN=D:/Projects/Niyah.Engine/build-warmup-final-seal/RelWithDebInfo/niyah-train.exe" "-DTOKENIZER=D:/Projects/Niyah.Engine/build-warmup-final-seal/niyah_train_fixture.tok" "-DSHARD=D:/Projects/Niyah.Engine/build-warmup-final-seal/niyah_train_fixture.srd" "-DWORK_DIR=D:/Projects/Niyah.Engine/build-warmup-final-seal" "-P" "D:/Projects/Niyah.Engine/tests/check_niyah_train_warmup_contract.cmake")
  set_tests_properties("niyah_train_warmup_contract_test" PROPERTIES  FIXTURES_REQUIRED "niyah_train_files" _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;575;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
else()
  add_test("niyah_train_warmup_contract_test" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("niyah_train_progress_details_test" "C:/Program Files/CMake/bin/cmake.exe" "-DNIYAH_TRAIN=D:/Projects/Niyah.Engine/build-warmup-final-seal/Debug/niyah-train.exe" "-DTOKENIZER=D:/Projects/Niyah.Engine/build-warmup-final-seal/niyah_train_fixture.tok" "-DSHARD=D:/Projects/Niyah.Engine/build-warmup-final-seal/niyah_train_fixture.srd" "-DWORK_DIR=D:/Projects/Niyah.Engine/build-warmup-final-seal" "-P" "D:/Projects/Niyah.Engine/tests/check_niyah_train_progress_details.cmake")
  set_tests_properties("niyah_train_progress_details_test" PROPERTIES  FIXTURES_REQUIRED "niyah_train_files" _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;585;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("niyah_train_progress_details_test" "C:/Program Files/CMake/bin/cmake.exe" "-DNIYAH_TRAIN=D:/Projects/Niyah.Engine/build-warmup-final-seal/Release/niyah-train.exe" "-DTOKENIZER=D:/Projects/Niyah.Engine/build-warmup-final-seal/niyah_train_fixture.tok" "-DSHARD=D:/Projects/Niyah.Engine/build-warmup-final-seal/niyah_train_fixture.srd" "-DWORK_DIR=D:/Projects/Niyah.Engine/build-warmup-final-seal" "-P" "D:/Projects/Niyah.Engine/tests/check_niyah_train_progress_details.cmake")
  set_tests_properties("niyah_train_progress_details_test" PROPERTIES  FIXTURES_REQUIRED "niyah_train_files" _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;585;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test("niyah_train_progress_details_test" "C:/Program Files/CMake/bin/cmake.exe" "-DNIYAH_TRAIN=D:/Projects/Niyah.Engine/build-warmup-final-seal/MinSizeRel/niyah-train.exe" "-DTOKENIZER=D:/Projects/Niyah.Engine/build-warmup-final-seal/niyah_train_fixture.tok" "-DSHARD=D:/Projects/Niyah.Engine/build-warmup-final-seal/niyah_train_fixture.srd" "-DWORK_DIR=D:/Projects/Niyah.Engine/build-warmup-final-seal" "-P" "D:/Projects/Niyah.Engine/tests/check_niyah_train_progress_details.cmake")
  set_tests_properties("niyah_train_progress_details_test" PROPERTIES  FIXTURES_REQUIRED "niyah_train_files" _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;585;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("niyah_train_progress_details_test" "C:/Program Files/CMake/bin/cmake.exe" "-DNIYAH_TRAIN=D:/Projects/Niyah.Engine/build-warmup-final-seal/RelWithDebInfo/niyah-train.exe" "-DTOKENIZER=D:/Projects/Niyah.Engine/build-warmup-final-seal/niyah_train_fixture.tok" "-DSHARD=D:/Projects/Niyah.Engine/build-warmup-final-seal/niyah_train_fixture.srd" "-DWORK_DIR=D:/Projects/Niyah.Engine/build-warmup-final-seal" "-P" "D:/Projects/Niyah.Engine/tests/check_niyah_train_progress_details.cmake")
  set_tests_properties("niyah_train_progress_details_test" PROPERTIES  FIXTURES_REQUIRED "niyah_train_files" _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;585;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
else()
  add_test("niyah_train_progress_details_test" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("niyah_train_resume_dataset_mismatch_test" "C:/Program Files/CMake/bin/cmake.exe" "-DNIYAH_TRAIN_EXE=D:/Projects/Niyah.Engine/build-warmup-final-seal/Debug/niyah-train.exe" "-DNIYAH_TRAIN_TOK=D:/Projects/Niyah.Engine/build-warmup-final-seal/niyah_train_fixture.tok" "-DNIYAH_TRAIN_SHARD=D:/Projects/Niyah.Engine/build-warmup-final-seal/niyah_train_fixture.srd" "-DNIYAH_TRAIN_SHARD_ALT=D:/Projects/Niyah.Engine/build-warmup-final-seal/niyah_train_fixture_alt.srd" "-DNIYAH_TRAIN_CKPT=D:/Projects/Niyah.Engine/build-warmup-final-seal/niyah_train_fixture_3.ckpt" "-DNIYAH_TRAIN_CUR=D:/Projects/Niyah.Engine/build-warmup-final-seal/niyah_train_fixture_3.cursor" "-P" "D:/Projects/Niyah.Engine/tests/check_train_resume_mismatch.cmake")
  set_tests_properties("niyah_train_resume_dataset_mismatch_test" PROPERTIES  FIXTURES_REQUIRED "niyah_train_files" _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;595;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("niyah_train_resume_dataset_mismatch_test" "C:/Program Files/CMake/bin/cmake.exe" "-DNIYAH_TRAIN_EXE=D:/Projects/Niyah.Engine/build-warmup-final-seal/Release/niyah-train.exe" "-DNIYAH_TRAIN_TOK=D:/Projects/Niyah.Engine/build-warmup-final-seal/niyah_train_fixture.tok" "-DNIYAH_TRAIN_SHARD=D:/Projects/Niyah.Engine/build-warmup-final-seal/niyah_train_fixture.srd" "-DNIYAH_TRAIN_SHARD_ALT=D:/Projects/Niyah.Engine/build-warmup-final-seal/niyah_train_fixture_alt.srd" "-DNIYAH_TRAIN_CKPT=D:/Projects/Niyah.Engine/build-warmup-final-seal/niyah_train_fixture_3.ckpt" "-DNIYAH_TRAIN_CUR=D:/Projects/Niyah.Engine/build-warmup-final-seal/niyah_train_fixture_3.cursor" "-P" "D:/Projects/Niyah.Engine/tests/check_train_resume_mismatch.cmake")
  set_tests_properties("niyah_train_resume_dataset_mismatch_test" PROPERTIES  FIXTURES_REQUIRED "niyah_train_files" _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;595;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test("niyah_train_resume_dataset_mismatch_test" "C:/Program Files/CMake/bin/cmake.exe" "-DNIYAH_TRAIN_EXE=D:/Projects/Niyah.Engine/build-warmup-final-seal/MinSizeRel/niyah-train.exe" "-DNIYAH_TRAIN_TOK=D:/Projects/Niyah.Engine/build-warmup-final-seal/niyah_train_fixture.tok" "-DNIYAH_TRAIN_SHARD=D:/Projects/Niyah.Engine/build-warmup-final-seal/niyah_train_fixture.srd" "-DNIYAH_TRAIN_SHARD_ALT=D:/Projects/Niyah.Engine/build-warmup-final-seal/niyah_train_fixture_alt.srd" "-DNIYAH_TRAIN_CKPT=D:/Projects/Niyah.Engine/build-warmup-final-seal/niyah_train_fixture_3.ckpt" "-DNIYAH_TRAIN_CUR=D:/Projects/Niyah.Engine/build-warmup-final-seal/niyah_train_fixture_3.cursor" "-P" "D:/Projects/Niyah.Engine/tests/check_train_resume_mismatch.cmake")
  set_tests_properties("niyah_train_resume_dataset_mismatch_test" PROPERTIES  FIXTURES_REQUIRED "niyah_train_files" _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;595;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("niyah_train_resume_dataset_mismatch_test" "C:/Program Files/CMake/bin/cmake.exe" "-DNIYAH_TRAIN_EXE=D:/Projects/Niyah.Engine/build-warmup-final-seal/RelWithDebInfo/niyah-train.exe" "-DNIYAH_TRAIN_TOK=D:/Projects/Niyah.Engine/build-warmup-final-seal/niyah_train_fixture.tok" "-DNIYAH_TRAIN_SHARD=D:/Projects/Niyah.Engine/build-warmup-final-seal/niyah_train_fixture.srd" "-DNIYAH_TRAIN_SHARD_ALT=D:/Projects/Niyah.Engine/build-warmup-final-seal/niyah_train_fixture_alt.srd" "-DNIYAH_TRAIN_CKPT=D:/Projects/Niyah.Engine/build-warmup-final-seal/niyah_train_fixture_3.ckpt" "-DNIYAH_TRAIN_CUR=D:/Projects/Niyah.Engine/build-warmup-final-seal/niyah_train_fixture_3.cursor" "-P" "D:/Projects/Niyah.Engine/tests/check_train_resume_mismatch.cmake")
  set_tests_properties("niyah_train_resume_dataset_mismatch_test" PROPERTIES  FIXTURES_REQUIRED "niyah_train_files" _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;595;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
else()
  add_test("niyah_train_resume_dataset_mismatch_test" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("niyah_train_multishard_test" "C:/Program Files/CMake/bin/cmake.exe" "-DNIYAH_TRAIN_EXE=D:/Projects/Niyah.Engine/build-warmup-final-seal/Debug/niyah-train.exe" "-DNIYAH_TRAIN_TOK=D:/Projects/Niyah.Engine/build-warmup-final-seal/niyah_train_fixture.tok" "-DNIYAH_TRAIN_SHARD_A=D:/Projects/Niyah.Engine/build-warmup-final-seal/niyah_train_fixture.srd" "-DNIYAH_TRAIN_SHARD_B=D:/Projects/Niyah.Engine/build-warmup-final-seal/niyah_train_fixture_alt.srd" "-DNIYAH_TRAIN_MULTI_PREFIX=D:/Projects/Niyah.Engine/build-warmup-final-seal/niyah_train_multishard" "-P" "D:/Projects/Niyah.Engine/tests/check_train_multishard.cmake")
  set_tests_properties("niyah_train_multishard_test" PROPERTIES  FIXTURES_REQUIRED "niyah_train_files" _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;607;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("niyah_train_multishard_test" "C:/Program Files/CMake/bin/cmake.exe" "-DNIYAH_TRAIN_EXE=D:/Projects/Niyah.Engine/build-warmup-final-seal/Release/niyah-train.exe" "-DNIYAH_TRAIN_TOK=D:/Projects/Niyah.Engine/build-warmup-final-seal/niyah_train_fixture.tok" "-DNIYAH_TRAIN_SHARD_A=D:/Projects/Niyah.Engine/build-warmup-final-seal/niyah_train_fixture.srd" "-DNIYAH_TRAIN_SHARD_B=D:/Projects/Niyah.Engine/build-warmup-final-seal/niyah_train_fixture_alt.srd" "-DNIYAH_TRAIN_MULTI_PREFIX=D:/Projects/Niyah.Engine/build-warmup-final-seal/niyah_train_multishard" "-P" "D:/Projects/Niyah.Engine/tests/check_train_multishard.cmake")
  set_tests_properties("niyah_train_multishard_test" PROPERTIES  FIXTURES_REQUIRED "niyah_train_files" _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;607;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test("niyah_train_multishard_test" "C:/Program Files/CMake/bin/cmake.exe" "-DNIYAH_TRAIN_EXE=D:/Projects/Niyah.Engine/build-warmup-final-seal/MinSizeRel/niyah-train.exe" "-DNIYAH_TRAIN_TOK=D:/Projects/Niyah.Engine/build-warmup-final-seal/niyah_train_fixture.tok" "-DNIYAH_TRAIN_SHARD_A=D:/Projects/Niyah.Engine/build-warmup-final-seal/niyah_train_fixture.srd" "-DNIYAH_TRAIN_SHARD_B=D:/Projects/Niyah.Engine/build-warmup-final-seal/niyah_train_fixture_alt.srd" "-DNIYAH_TRAIN_MULTI_PREFIX=D:/Projects/Niyah.Engine/build-warmup-final-seal/niyah_train_multishard" "-P" "D:/Projects/Niyah.Engine/tests/check_train_multishard.cmake")
  set_tests_properties("niyah_train_multishard_test" PROPERTIES  FIXTURES_REQUIRED "niyah_train_files" _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;607;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("niyah_train_multishard_test" "C:/Program Files/CMake/bin/cmake.exe" "-DNIYAH_TRAIN_EXE=D:/Projects/Niyah.Engine/build-warmup-final-seal/RelWithDebInfo/niyah-train.exe" "-DNIYAH_TRAIN_TOK=D:/Projects/Niyah.Engine/build-warmup-final-seal/niyah_train_fixture.tok" "-DNIYAH_TRAIN_SHARD_A=D:/Projects/Niyah.Engine/build-warmup-final-seal/niyah_train_fixture.srd" "-DNIYAH_TRAIN_SHARD_B=D:/Projects/Niyah.Engine/build-warmup-final-seal/niyah_train_fixture_alt.srd" "-DNIYAH_TRAIN_MULTI_PREFIX=D:/Projects/Niyah.Engine/build-warmup-final-seal/niyah_train_multishard" "-P" "D:/Projects/Niyah.Engine/tests/check_train_multishard.cmake")
  set_tests_properties("niyah_train_multishard_test" PROPERTIES  FIXTURES_REQUIRED "niyah_train_files" _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;607;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
else()
  add_test("niyah_train_multishard_test" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("niyah_train_pair_mismatch_test" "C:/Program Files/CMake/bin/cmake.exe" "-DNIYAH_TRAIN_EXE=D:/Projects/Niyah.Engine/build-warmup-final-seal/Debug/niyah-train.exe" "-DNIYAH_TRAIN_TOK=D:/Projects/Niyah.Engine/build-warmup-final-seal/niyah_train_fixture.tok" "-DNIYAH_TRAIN_SHARD=D:/Projects/Niyah.Engine/build-warmup-final-seal/niyah_train_fixture.srd" "-DNIYAH_TRAIN_PAIR_PREFIX=D:/Projects/Niyah.Engine/build-warmup-final-seal/niyah_train_pair" "-P" "D:/Projects/Niyah.Engine/tests/check_train_pair_mismatch.cmake")
  set_tests_properties("niyah_train_pair_mismatch_test" PROPERTIES  FIXTURES_REQUIRED "niyah_train_files" _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;618;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("niyah_train_pair_mismatch_test" "C:/Program Files/CMake/bin/cmake.exe" "-DNIYAH_TRAIN_EXE=D:/Projects/Niyah.Engine/build-warmup-final-seal/Release/niyah-train.exe" "-DNIYAH_TRAIN_TOK=D:/Projects/Niyah.Engine/build-warmup-final-seal/niyah_train_fixture.tok" "-DNIYAH_TRAIN_SHARD=D:/Projects/Niyah.Engine/build-warmup-final-seal/niyah_train_fixture.srd" "-DNIYAH_TRAIN_PAIR_PREFIX=D:/Projects/Niyah.Engine/build-warmup-final-seal/niyah_train_pair" "-P" "D:/Projects/Niyah.Engine/tests/check_train_pair_mismatch.cmake")
  set_tests_properties("niyah_train_pair_mismatch_test" PROPERTIES  FIXTURES_REQUIRED "niyah_train_files" _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;618;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test("niyah_train_pair_mismatch_test" "C:/Program Files/CMake/bin/cmake.exe" "-DNIYAH_TRAIN_EXE=D:/Projects/Niyah.Engine/build-warmup-final-seal/MinSizeRel/niyah-train.exe" "-DNIYAH_TRAIN_TOK=D:/Projects/Niyah.Engine/build-warmup-final-seal/niyah_train_fixture.tok" "-DNIYAH_TRAIN_SHARD=D:/Projects/Niyah.Engine/build-warmup-final-seal/niyah_train_fixture.srd" "-DNIYAH_TRAIN_PAIR_PREFIX=D:/Projects/Niyah.Engine/build-warmup-final-seal/niyah_train_pair" "-P" "D:/Projects/Niyah.Engine/tests/check_train_pair_mismatch.cmake")
  set_tests_properties("niyah_train_pair_mismatch_test" PROPERTIES  FIXTURES_REQUIRED "niyah_train_files" _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;618;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("niyah_train_pair_mismatch_test" "C:/Program Files/CMake/bin/cmake.exe" "-DNIYAH_TRAIN_EXE=D:/Projects/Niyah.Engine/build-warmup-final-seal/RelWithDebInfo/niyah-train.exe" "-DNIYAH_TRAIN_TOK=D:/Projects/Niyah.Engine/build-warmup-final-seal/niyah_train_fixture.tok" "-DNIYAH_TRAIN_SHARD=D:/Projects/Niyah.Engine/build-warmup-final-seal/niyah_train_fixture.srd" "-DNIYAH_TRAIN_PAIR_PREFIX=D:/Projects/Niyah.Engine/build-warmup-final-seal/niyah_train_pair" "-P" "D:/Projects/Niyah.Engine/tests/check_train_pair_mismatch.cmake")
  set_tests_properties("niyah_train_pair_mismatch_test" PROPERTIES  FIXTURES_REQUIRED "niyah_train_files" _BACKTRACE_TRIPLES "D:/Projects/Niyah.Engine/CMakeLists.txt;618;add_test;D:/Projects/Niyah.Engine/CMakeLists.txt;0;")
else()
  add_test("niyah_train_pair_mismatch_test" NOT_AVAILABLE)
endif()
